import { createFileRoute, Link } from "@tanstack/react-router";
import { Masthead } from "@/components/masthead";
import { DeveloperNav } from "@/components/developer-nav";
const capabilities = [
  ["สรุปประจำวัน", "Briefs, data window, completeness", "/api/public/v1/briefs", "get_today_brief"],
  ["การเปลี่ยนแปลงสำคัญ", "Signals และเหตุการณ์ที่แก้ไข/ถอน", "/api/public/v1/signals", "list_signals"],
  ["ค่าที่เก็บได้จริง", "Observations, weather, dams", "/api/public/v1/observations", "get_observations"],
  ["ที่มาและคุณภาพ", "Sources, health, evidence metadata", "/api/public/v1/sources", "list_sources"],
  ["ปฏิทินสาธารณะ", "วันหยุด ภาษี และกำหนดเผยแพร่", "/api/public/v1/holidays", "get_calendar"],
  ["บริบทประกอบ", "Social และข่าว (ไม่ใช่ Signal)", "/api/public/v1/social", "list_social_updates"],
];
export const Route = createFileRoute("/developers/")({ staticData: { sitemap: true }, head: () => ({ meta: [
  { title: "Developer Document — Thailand Daily Signals" }, { name: "description", content: "คู่มือ Public API, OpenAPI และ MCP สำหรับนักพัฒนาและ AI Agents" },
  { property: "og:title", content: "Developer Document — Thailand Daily Signals" }, { property: "og:description", content: "Capability-aware interface สำหรับอ่าน Signals, Briefs และหลักฐานสาธารณะ" }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: Developers });
function Developers() { return <div className="min-h-screen"><Masthead /><main className="mx-auto max-w-6xl px-4 py-8"><header className="max-w-3xl"><p className="text-sm font-semibold text-primary">FOR HUMANS & AI AGENTS</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">Developer Document</h1><p className="mt-3 text-muted-foreground">เลือกความสามารถที่ต้องการ แล้วใช้ REST API หรือ MCP จากสัญญาข้อมูลชุดเดียวกัน ทั้งหมดเป็นข้อมูลสาธารณะแบบอ่านอย่างเดียว ไม่ต้องเข้าสู่ระบบ</p></header><DeveloperNav />
<section className="mt-10"><h2 className="font-display text-2xl">ความสามารถที่เปิดให้ใช้</h2><div className="mt-4 overflow-x-auto"><table className="min-w-[720px] w-full text-sm"><thead><tr className="border-b-2 border-foreground text-left"><th className="py-2">ต้องการทำอะไร</th><th>ข้อมูลที่ได้</th><th>REST</th><th>MCP</th></tr></thead><tbody>{capabilities.map(([want, data, rest, mcp]) => <tr key={want} className="border-b border-border"><td className="py-3 font-semibold">{want}</td><td>{data}</td><td><code>{rest}</code></td><td><code>{mcp}</code></td></tr>)}</tbody></table></div></section>
<section className="mt-10 grid gap-8 md:grid-cols-2"><div><h2 className="font-display text-2xl">เริ่มต้นเร็ว</h2><pre className="mt-3 overflow-x-auto border border-border bg-muted p-4 text-xs"><code>{`curl 'https://thailands-daily-pulse.lovable.app/api/public/v1/signals?limit=10'`}</code></pre><p className="mt-3 text-sm">ดูรายละเอียดและตัวอย่างภาษาอื่นในหน้า <Link to="/developers/api" className="underline">Public API</Link></p></div><div><h2 className="font-display text-2xl">ข้อจำกัดสำคัญ</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm"><li>ไม่เปิดคำสั่งดึงข้อมูล เผยแพร่ Brief, backfill, queue หรือตั้งค่า</li><li>ไม่เปิดไฟล์หลักฐานดิบหรือลิงก์ชั่วคราว เปิดเฉพาะ metadata</li><li>ข่าวและ Social เป็นบริบท ไม่ใช่ Signal และไม่เพิ่มคะแนน</li><li>สูงสุด 100 รายการต่อคำขอ เวลารายงานอ้างอิง Asia/Bangkok</li></ul></div></section>
<section className="mt-10"><h2 className="font-display text-2xl">ความหมายของเวลาและคุณภาพ</h2><dl className="mt-3 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="font-semibold">observed_on / period</dt><dd className="text-muted-foreground">วันที่ข้อมูลกล่าวถึง</dd></div><div><dt className="font-semibold">published_at</dt><dd className="text-muted-foreground">เวลาที่ต้นทางเผยแพร่</dd></div><div><dt className="font-semibold">received_at</dt><dd className="text-muted-foreground">เวลาที่ระบบได้รับ ใช้ตัด cutoff 05:45</dd></div><div><dt className="font-semibold">effective_from</dt><dd className="text-muted-foreground">วันที่เริ่มมีผลจริง</dd></div><div><dt className="font-semibold">is_demo / is_live</dt><dd className="text-muted-foreground">แยกข้อมูลตัวอย่างออกจากข้อมูลจริง</dd></div><div><dt className="font-semibold">version / status</dt><dd className="text-muted-foreground">ติดตามการแก้ไขและถอนเหตุการณ์ย้อนหลัง</dd></div></dl></section></main></div>; }
