import { createFileRoute } from "@tanstack/react-router";
import { Masthead } from "@/components/masthead";
import { DeveloperNav } from "@/components/developer-nav";
import { API_RESOURCES } from "@/lib/openapi";
export const Route = createFileRoute("/developers/api")({ staticData: { sitemap: true }, head: () => ({ meta: [
  { title: "Public API v1 — Thailand Daily Signals" }, { name: "description", content: "REST API แบบอ่านอย่างเดียว พร้อม OpenAPI 3.1 สำหรับข้อมูลสัญญาณรายวันของประเทศไทย" }, { property: "og:title", content: "Public API v1 — Thailand Daily Signals" }, { property: "og:description", content: "Endpoint, parameters, schemas และตัวอย่างเรียกข้อมูลสาธารณะ" }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: ApiDocs });
function ApiDocs() { const base = "https://thailands-daily-pulse.lovable.app/api/public/v1"; return <div className="min-h-screen"><Masthead /><main className="page-shell"><h1 className="font-editorial text-4xl sm:text-5xl">Public API v1</h1><p className="mt-3 max-w-3xl text-muted-foreground">GET เท่านั้น ไม่ต้องใช้กุญแจ API ผลลัพธ์มี <code>data</code> และ <code>meta</code> รูปแบบข้อผิดพลาดคือ <code>{`{"error":{"code":"...","message":"..."}}`}</code></p><DeveloperNav />
<section className="mt-10"><h2 className="section-heading text-2xl">Endpoints</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{API_RESOURCES.map(([path, text]) => <a key={path} href={`/api/public/v1/${path}?limit=5`} className="border-t-2 border-editorial-ink bg-editorial-surface p-4 shadow-[var(--shadow-editorial)] hover:bg-card"><code className="font-semibold text-editorial-red">GET /{path}</code><p className="mt-1 text-sm text-muted-foreground">{text}</p></a>)}</div></section>
<section className="mt-10 grid gap-8 lg:grid-cols-2"><div><h2 className="section-heading text-2xl">Parameters</h2><ul className="mt-3 space-y-2 text-sm"><li><code>limit</code> 1–100 (ค่าเริ่มต้น 25)</li><li><code>date</code> รูปแบบ YYYY-MM-DD เมื่อ endpoint รองรับ</li><li><code>id</code> ใช้กรอง event, metric, source หรือ station ตาม resource</li></ul></div><div><h2 className="section-heading text-2xl">Version & cache</h2><p className="mt-3 text-sm">เวอร์ชันอยู่ใน URL ที่ <code>/v1</code> และ response อาจถูกเก็บ cache 60 วินาที การเปลี่ยนสัญญาที่เข้ากันไม่ได้จะออกเวอร์ชันใหม่</p></div></section>
<section className="mt-10"><h2 className="section-heading text-2xl">ตัวอย่าง</h2><div className="mt-3 grid gap-4"><Code title="curl" value={`curl '${base}/briefs?limit=1'`} /><Code title="JavaScript" value={`const r = await fetch('${base}/signals?date=2026-10-03');\nconst { data, meta } = await r.json();`} /><Code title="Python" value={`import requests\ndata = requests.get('${base}/observations', params={'limit': 20}).json()`} /></div></section></main></div>; }
function Code({ title, value }: { title: string; value: string }) { return <div><p className="text-xs font-semibold uppercase text-muted-foreground">{title}</p><pre className="mt-1 overflow-x-auto border-t-2 border-editorial-ink bg-editorial-surface p-4 text-xs"><code>{value}</code></pre></div>; }
