import { createFileRoute } from "@tanstack/react-router";
import { Masthead } from "@/components/masthead";
import { DeveloperNav } from "@/components/developer-nav";
const tools = ["get_today_brief", "get_brief_by_date", "compare_briefs", "list_signals", "get_signal", "list_signal_events", "get_household_impact", "list_sources", "get_source_health", "get_observations", "get_dam_levels", "get_weather_observations", "get_latest_lottery", "list_social_updates", "list_news_mentions", "get_calendar", "get_evidence_metadata"];
export const Route = createFileRoute("/developers/mcp")({ staticData: { sitemap: true }, head: () => ({ meta: [
  { title: "MCP Server — Thailand Daily Signals" }, { name: "description", content: "เครื่องมือ MCP สาธารณะ 17 รายการสำหรับ AI Agents อ่าน Daily Brief, Signals และหลักฐาน" }, { property: "og:title", content: "MCP Server — Thailand Daily Signals" }, { property: "og:description", content: "เชื่อม AI Agents เข้ากับข้อมูลสาธารณะแบบอ่านอย่างเดียวผ่าน Model Context Protocol" }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: McpDocs });
function McpDocs() { return <div className="min-h-screen"><Masthead /><main className="page-shell"><h1 className="font-editorial text-4xl sm:text-5xl">MCP Server</h1><p className="mt-3 max-w-3xl text-muted-foreground">ให้ AI Agents ค้นและเรียกเครื่องมือข้อมูลได้ทันทีผ่าน Streamable HTTP แบบสาธารณะ อ่านอย่างเดียว และไม่ต้องเข้าสู่ระบบ</p><DeveloperNav />
<section className="mt-10 grid gap-8 md:grid-cols-2"><div><h2 className="section-heading text-2xl">การเชื่อมต่อ</h2><dl className="mt-3 text-sm"><dt className="font-semibold">Endpoint</dt><dd><code>https://thailands-daily-pulse.lovable.app/mcp</code></dd><dt className="mt-3 font-semibold">ชื่อ server</dt><dd><code>thailand-daily-signals</code></dd><dt className="mt-3 font-semibold">Transport</dt><dd>Streamable HTTP — POST พร้อม <code>Accept: application/json, text/event-stream</code></dd></dl></div><div><h2 className="section-heading text-2xl">ขอบเขตความปลอดภัย</h2><p className="mt-3 text-sm">ทุก tool มีป้าย read-only และ idempotent ไม่มี tool สำหรับ ingest, publish, rerun, backfill, สร้างภาพ, settings, queue, jobs หรือไฟล์หลักฐานส่วนตัว</p></div></section>
<section className="mt-10"><h2 className="section-heading text-2xl">Tool catalog ({tools.length})</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{tools.map((tool, i) => <div key={tool} className="border-b border-editorial-rule py-3 text-sm"><span className="mr-2 text-muted-foreground">{String(i + 1).padStart(2, "0")}</span><code className="font-semibold">{tool}</code></div>)}</div></section>
<section className="mt-10"><h2 className="section-heading text-2xl">ตัวอย่างคำขอ</h2><pre className="mt-3 overflow-x-auto border-t-2 border-editorial-ink bg-editorial-surface p-4 text-xs"><code>{`curl -X POST https://thailands-daily-pulse.lovable.app/mcp \\\n  -H 'Content-Type: application/json' \\\n  -H 'Accept: application/json, text/event-stream' \\\n  -d '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"get_today_brief","arguments":{}}}'`}</code></pre><p className="mt-3 text-sm text-muted-foreground">ผลลัพธ์ทุก tool มี structured JSON และระบุ timezone Asia/Bangkok ข่าวและ Social จะมีคำกำกับว่าเป็นบริบทเท่านั้น</p></section></main></div>; }
