import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Masthead } from "@/components/masthead";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";

// Self-host setup: everything runs in the visitor's browser. Keys typed here are never sent
// to this site's server — the connection test calls the visitor's own database directly.

export const Route = createFileRoute("/setup")({
  ssr: false,
  head: () => ({
    meta: [
      { title: "ตั้งค่าฐานข้อมูลสำหรับติดตั้งเอง — Thailand Daily Signals" },
      { name: "description", content: "เชื่อมเว็บที่คุณติดตั้งเองเข้ากับฐานข้อมูลของคุณ ทดสอบการเชื่อมต่อ และสร้างไฟล์ตั้งค่าพร้อมใช้" },
      { property: "og:title", content: "ตั้งค่าฐานข้อมูลสำหรับติดตั้งเอง" },
      { property: "og:description", content: "ทดสอบฐานข้อมูลของคุณเองและสร้างไฟล์ .env สำหรับ Cloudflare, Docker หรือเซิร์ฟเวอร์ทั่วไป" },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: Setup,
});

type Check = { name: string; ok: boolean; detail: string };
const TABLES: [string, string, number][] = [
  ["families", "หมวดข้อมูล", 13],
  ["metrics", "ตัวชี้วัดและเกณฑ์", 56],
  ["source_registry", "รายชื่อแหล่งข้อมูล", 29],
];

const rand = () => Array.from(crypto.getRandomValues(new Uint8Array(32)), (b) => b.toString(16).padStart(2, "0")).join("");

function Setup() {
  const current = (import.meta.env["VITE_SUPABASE_URL"] as string | undefined) ?? "";
  const [f, setF] = useState({ url: "", anon: "", service: "", site: "", email: "", cron: rand(), ai: "", firecrawl: "" });
  const [checks, setChecks] = useState<Check[] | null>(null);
  const [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState("");
  const set = (k: keyof typeof f) => (e: React.ChangeEvent<HTMLInputElement>) => setF({ ...f, [k]: e.target.value.trim() });
  const url = f.url.replace(/\/+$/, "");
  const ref = (() => { try { return new URL(url).hostname.split(".")[0]; } catch { return ""; } })();
  const sameAsThisSite = !!current && url === current.replace(/\/+$/, "");

  const test = async () => {
    setBusy(true); setChecks(null);
    const out: Check[] = [];
    try { new URL(url); } catch { setChecks([{ name: "URL", ok: false, detail: "รูปแบบ URL ไม่ถูกต้อง" }]); setBusy(false); return; }
    const h = { apikey: f.anon, ...(f.anon.startsWith("sb_") ? {} : { Authorization: `Bearer ${f.anon}` }) };
    for (const [t, label, expect] of TABLES) {
      try {
        const r = await fetch(`${url}/rest/v1/${t}?select=*&limit=1`, { headers: { ...h, Prefer: "count=exact", Range: "0-0" } });
        if (r.status === 401 || r.status === 403) { out.push({ name: label, ok: false, detail: "คีย์ไม่ถูกต้อง หรือยังไม่ได้ให้สิทธิ์อ่าน" }); continue; }
        if (r.status === 404) { out.push({ name: label, ok: false, detail: "ยังไม่มีตาราง — รัน scripts/setup-db.sh ก่อน" }); continue; }
        const n = Number(r.headers.get("content-range")?.split("/")[1] ?? 0);
        out.push({ name: label, ok: n > 0, detail: n > 0 ? `พบ ${n} แถว (ชุดตั้งต้นมี ${expect})` : "ตารางว่าง — รัน database/seed.sql" });
      } catch {
        out.push({ name: label, ok: false, detail: "เชื่อมต่อไม่ได้ (ตรวจ URL หรือการตั้งค่า CORS ของ Supabase ที่ติดตั้งเอง)" });
      }
    }
    setChecks(out); setBusy(false);
  };

  const env = useMemo(() => `# Generated by /setup — keep this file private
VITE_SUPABASE_URL=${url}
VITE_SUPABASE_PUBLISHABLE_KEY=${f.anon}
VITE_SUPABASE_PROJECT_ID=${ref}
SUPABASE_URL=${url}
SUPABASE_PUBLISHABLE_KEY=${f.anon}
SUPABASE_SERVICE_ROLE_KEY=${f.service}
LOVABLE_CRON_SECRET=${f.cron}
VITE_SITE_URL=${f.site}
VITE_ADMIN_EMAIL=${f.email}
AI_BASE_URL=
AI_API_KEY=${f.ai}
FIRECRAWL_API_KEY=${f.firecrawl}
`, [url, f, ref]);

  const wrangler = useMemo(() => [
    ["SUPABASE_URL", url], ["SUPABASE_PUBLISHABLE_KEY", f.anon], ["SUPABASE_SERVICE_ROLE_KEY", f.service], ["LOVABLE_CRON_SECRET", f.cron],
    ...(f.ai ? [["AI_API_KEY", f.ai]] : []), ...(f.firecrawl ? [["FIRECRAWL_API_KEY", f.firecrawl]] : []),
  ].map(([k]) => `npx wrangler@4 secret put ${k}`).join("\n") + "\nnpx wrangler@4 deploy", [url, f]);

  const dbCmd = `DATABASE_URL='postgresql://postgres:PASSWORD@HOST:5432/postgres' \\\nSITE_URL='${f.site || "https://your-site"}' CRON_SECRET='${f.cron}' \\\n./scripts/setup-db.sh`;

  const copy = (k: string, v: string) => { navigator.clipboard.writeText(v); setCopied(k); setTimeout(() => setCopied(""), 1500); };
  const download = () => {
    const a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([env], { type: "text/plain" })); a.download = ".env"; a.click();
  };
  const allOk = checks?.every((c) => c.ok);
  const field = (k: keyof typeof f, label: string, hint: string, type = "text") => (
    <div className="space-y-1">
      <Label htmlFor={k}>{label}</Label>
      <Input id={k} type={type} value={f[k]} onChange={set(k)} autoComplete="off" spellCheck={false} />
      <p className="text-xs text-muted-foreground">{hint}</p>
    </div>
  );
  const Block = ({ id, title, text }: { id: string; title: string; text: string }) => (
    <div className="space-y-2">
      <div className="flex items-center justify-between"><h3 className="font-semibold">{title}</h3>
        <Button size="sm" variant="outline" onClick={() => copy(id, text)}>{copied === id ? "คัดลอกแล้ว" : "คัดลอก"}</Button></div>
      <pre className="overflow-x-auto rounded border border-border bg-muted p-3 text-xs">{text}</pre>
    </div>
  );

  return (
    <div className="min-h-screen bg-background">
      <Masthead />
      <main className="mx-auto max-w-3xl space-y-8 px-4 py-8">
        <header className="space-y-2">
          <h1 className="font-serif text-3xl font-bold">ตั้งค่าฐานข้อมูลสำหรับติดตั้งเอง</h1>
          <p className="text-muted-foreground">สำหรับผู้ที่นำโค้ดจาก GitHub ไปติดตั้งบนเซิร์ฟเวอร์ของตัวเอง ใส่ข้อมูลฐานข้อมูล <b>ของคุณ</b> ทดสอบการเชื่อมต่อ แล้วนำไฟล์ตั้งค่าที่ได้ไปใช้ — ไม่ต้องใช้ฐานข้อมูลของโครงการนี้</p>
          <p className="rounded border border-border bg-muted p-3 text-sm">ความปลอดภัย: ทุกอย่างในหน้านี้ทำงานในเบราว์เซอร์ของคุณเท่านั้น คีย์ที่พิมพ์จะไม่ถูกส่งหรือบันทึกที่เซิร์ฟเวอร์ใด การทดสอบเรียกไปยังฐานข้อมูลของคุณโดยตรง</p>
          <p className="text-sm text-muted-foreground">เว็บนี้เชื่อมกับ: {current ? new URL(current).hostname : "ยังไม่ได้ตั้งค่า"} · คู่มือเต็มอยู่ในไฟล์ docs/deployment.md ของโค้ด</p>
        </header>

        <section className="space-y-4">
          <h2 className="border-b border-border pb-1 text-xl font-bold text-primary">1. ฐานข้อมูลของคุณ</h2>
          {field("url", "Supabase URL", "Supabase Cloud: Project Settings → API · ติดตั้งเอง: ค่า API_EXTERNAL_URL")}
          {field("anon", "Publishable / anon key", "คีย์สาธารณะ ใช้ในเบราว์เซอร์ได้", "password")}
          {field("service", "Service role / secret key", "ใช้ฝั่งเซิร์ฟเวอร์เท่านั้น — หน้านี้ไม่ทดสอบและไม่ส่งคีย์นี้ไปที่ใด", "password")}
          {sameAsThisSite && <p className="text-sm text-primary">นี่คือฐานข้อมูลของเว็บนี้ — สำหรับการติดตั้งเองควรใช้ฐานข้อมูลของคุณเอง</p>}
          <Button onClick={test} disabled={busy || !f.url || !f.anon}>{busy ? "กำลังทดสอบ…" : "ทดสอบการเชื่อมต่อ"}</Button>
          {checks && (
            <ul className="space-y-1 text-sm">
              {checks.map((c) => <li key={c.name}><b className={c.ok ? "" : "text-primary"}>{c.ok ? "ผ่าน" : "ไม่ผ่าน"}</b> · {c.name} — {c.detail}</li>)}
              <li className="pt-1 font-semibold">{allOk ? "ฐานข้อมูลพร้อมใช้งาน" : "ยังไม่พร้อม — ดูขั้นตอนที่ 3 เพื่อสร้างตาราง"}</li>
            </ul>
          )}
        </section>

        <section className="space-y-4">
          <h2 className="border-b border-border pb-1 text-xl font-bold text-primary">2. เว็บไซต์และบริการเสริม</h2>
          {field("site", "URL เว็บของคุณ", "เช่น https://signals.example.org")}
          {field("email", "อีเมลผู้ดูแล", "ชื่อผู้ใช้ admin ในหน้าเข้าสู่ระบบจะใช้อีเมลนี้")}
          {field("cron", "รหัสลับงานตามเวลา", "สุ่มให้แล้ว ใช้ค่าเดียวกันในฐานข้อมูลและเว็บ")}
          {field("ai", "AI API key (ไม่บังคับ)", "ไม่ใส่ก็ได้ — ฟีเจอร์ AI จะหยุด ส่วนอื่นทำงานปกติ", "password")}
          {field("firecrawl", "Firecrawl key (ไม่บังคับ)", "สำหรับเว็บที่บล็อกการดึงตรง เช่น X", "password")}
        </section>

        <section className="space-y-5">
          <h2 className="border-b border-border pb-1 text-xl font-bold text-primary">3. นำไปใช้</h2>
          <Block id="db" title="สร้างตารางและตั้งเวลา (ครั้งแรก)" text={dbCmd} />
          <div className="space-y-2">
            <Block id="env" title=".env — สำหรับเครื่องตัวเอง / Docker" text={env} />
            <Button size="sm" onClick={download}>ดาวน์โหลด .env</Button>
          </div>
          <Block id="cf" title="Cloudflare Workers" text={`bun run build\n${wrangler}`} />
          <Block id="docker" title="Docker" text="docker compose up -d --build   # อ่านค่าจาก .env" />
          <p className="text-sm text-muted-foreground">ค่าที่ขึ้นต้นด้วย VITE_ ถูกฝังตอน build — แก้แล้วต้อง build ใหม่ จากนั้นสร้างผู้ดูแลด้วย database/create-admin.sql และเข้า <Link to="/admin/login" className="underline">/admin/login</Link></p>
        </section>
      </main>
    </div>
  );
}
