-- Thailand Daily Signals — database structure (public schema)
-- Generated by scripts/export-db.sh from the live database. Do not edit by hand; add a migration instead.
-- Prerequisites: Supabase (cloud or self-hosted) — provides roles anon/authenticated/service_role,
-- the auth schema, storage and the pg_cron + pg_net extensions. For plain Postgres see database/README.md.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;
--
-- PostgreSQL database dump
--


-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--



--
-- Name: app_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.app_role AS ENUM (
    'admin',
    'user'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ingest_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingest_jobs (
    id bigint NOT NULL,
    batch_id uuid NOT NULL,
    source text NOT NULL,
    job_type text NOT NULL,
    run_kind text DEFAULT 'hourly'::text NOT NULL,
    status text DEFAULT 'queued'::text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 3 NOT NULL,
    run_after timestamp with time zone DEFAULT now() NOT NULL,
    locked_until timestamp with time zone,
    rows integer DEFAULT 0 NOT NULL,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone
);


--
-- Name: claim_ingest_job(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.claim_ingest_job() RETURNS SETOF public.ingest_jobs
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
  RETURN QUERY
  UPDATE public.ingest_jobs j SET status = 'running', attempts = j.attempts + 1, started_at = now(), locked_until = now() + interval '3 minutes'
  WHERE j.id = (
    SELECT id FROM public.ingest_jobs
    WHERE (status = 'queued' AND run_after <= now()) OR (status = 'running' AND locked_until < now())
    ORDER BY run_after, id LIMIT 1 FOR UPDATE SKIP LOCKED
  )
  RETURNING j.*;
END $$;


--
-- Name: detect_core(date, timestamp with time zone); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.detect_core(_d date, _cutoff timestamp with time zone DEFAULT NULL::timestamp with time zone) RETURNS TABLE(family_id text, metric_id text, severity text, title text, prev_value numeric, new_value numeric, change_abs numeric, change_pct numeric, is_demo boolean, checks jsonb, has_obs boolean)
    LANGUAGE plpgsql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
declare r record; prev numeric; prev_d date; cur numeric; cur_d date; ch numeric; pct numeric; ratio numeric; tmul numeric;
  sev text; ttl text; bp int; bc int; dem boolean; chk jsonb; sd numeric; npts int; z numeric;
  cavg numeric; pavg numeric; cn int; pn int; wpct numeric; wr numeric; wsev text; cf numeric; lagd int;
begin
  for r in select m.*, f.trust from metrics m join families f on f.id = m.family_id loop
    cur := null; cur_d := null;
    lagd := case when r.weekly then greatest(r.lag_days, 1) else 0 end;
    select o.value, o.is_demo, o.observed_on into cur, dem, cur_d from observations o
      where o.metric_id = r.id and o.observed_on between _d - lagd and _d
        and (_cutoff is null or o.received_at <= _cutoff)
      order by o.observed_on desc limit 1;
    if cur is null then continue; end if;
    prev := null; prev_d := null;
    select o.value, o.observed_on into prev, prev_d from observations o where o.metric_id = r.id and o.observed_on < cur_d and (_cutoff is null or o.received_at <= _cutoff) order by o.observed_on desc limit 1;
    sev := null; ch := null; pct := null; sd := null; z := null;
    tmul := case r.trust when 'medium' then 1.5 else 1 end;
    chk := jsonb_build_object('trust', r.trust, 'compared_with', prev_d, 'gap_days', case when prev_d is null then null else cur_d - prev_d end, 'max_gap_days', r.max_gap_days, 'demo', dem, 'price_date', cur_d, 'lag_days', lagd);
    if r.kind = 'events' then
      if cur >= r.bands[1] then
        sev := case when array_length(r.bands, 1) >= 2 and cur >= r.bands[2] then 'high' else 'medium' end;
        ttl := format('%s %s ครั้ง', r.name_th, round(cur, 0));
        chk := chk || jsonb_build_object('rule', 'events', 'bands', r.bands, 'count', cur);
      end if;
      family_id := r.family_id; metric_id := r.id; severity := sev; title := ttl; prev_value := prev; new_value := cur;
      change_abs := case when prev is null then null else cur - prev end; change_pct := null; is_demo := dem; checks := chk; has_obs := true;
      return next; continue;
    end if;
    if prev_d is not null and (cur_d - prev_d) > r.max_gap_days and r.kind <> 'release' then
      family_id := r.family_id; metric_id := r.id; severity := null; has_obs := true; return next; continue;
    end if;
    if r.kind = 'release' then
      ch := case when prev is null then null else cur - prev end;
      sev := 'medium';
      ttl := format('%s ประกาศใหม่: %s %s', r.name_th, round(cur, r.decimals), r.unit);
      chk := chk || jsonb_build_object('rule', 'release');
    elsif prev is not null then
      ch := cur - prev;
      pct := case when prev = 0 then null else ch / abs(prev) * 100 end;
      if r.kind = 'level' then
        select count(*) into bp from unnest(r.bands) b where prev >= b;
        select count(*) into bc from unnest(r.bands) b where cur >= b;
        if bc <> bp then
          sev := case when bc >= 2 then 'high' when bc > bp then 'medium' else 'low' end;
          ttl := format('%s %s ระดับ: %s → %s %s', r.name_th, case when bc > bp then 'ข้าม' else 'ลดลงต่ำกว่า' end, round(prev, r.decimals), round(cur, r.decimals), r.unit);
          chk := chk || jsonb_build_object('rule', 'level', 'bands', r.bands);
        end if;
      else
        select stddev_samp(d), count(d) into sd, npts from (
          select t.value - lag(t.value) over (order by t.observed_on) as d
          from (select o.value, o.observed_on from observations o where o.metric_id = r.id and o.observed_on < cur_d and o.is_demo = dem and (_cutoff is null or o.received_at <= _cutoff) order by o.observed_on desc limit 31) t
        ) x where d is not null;
        ratio := greatest(
          case when r.threshold_abs is not null and r.threshold_abs > 0 then abs(ch) / r.threshold_abs else 0 end,
          case when r.threshold_pct is not null and pct is not null then abs(pct) / r.threshold_pct else 0 end) / tmul;
        if r.min_pct is not null and (pct is null or abs(pct) < r.min_pct) then ratio := 0; end if;
        if sd is not null and sd > 0 and npts >= 10 then
          z := abs(ch) / sd;
          if z < r.vol_k then ratio := least(ratio, 0); end if;
        end if;
        if ratio >= 1 then
          ratio := greatest(ratio, coalesce(z / r.vol_k, 0));
          sev := case when ratio >= 3 then 'high' when ratio >= 1.5 then 'medium' else 'low' end;
          ttl := format('%s %s %s → %s %s', r.name_th, case when ch > 0 then 'ขึ้น' else 'ลง' end, round(prev, r.decimals), round(cur, r.decimals), r.unit);
          chk := chk || jsonb_build_object('rule', 'delta', 'ratio', round(ratio, 2), 'threshold_abs', r.threshold_abs, 'threshold_pct', r.threshold_pct,
                   'min_pct', r.min_pct, 'trust_multiplier', tmul, 'sd', round(sd, 4), 'z', round(z, 2), 'vol_k', r.vol_k, 'vol_points', npts);
        end if;
      end if;
    end if;
    if r.weekly and r.kind = 'delta' and r.threshold_pct is not null then
      select avg(o.value), count(*) into cavg, cn from observations o where o.metric_id = r.id and o.is_demo = dem
        and o.observed_on between cur_d - 6 and cur_d and (_cutoff is null or o.received_at <= _cutoff);
      select avg(o.value), count(*) into pavg, pn from observations o where o.metric_id = r.id and o.is_demo = dem
        and o.observed_on between cur_d - 13 and cur_d - 7 and (_cutoff is null or o.received_at <= _cutoff);
      if cn >= 3 and pn >= 3 and pavg <> 0 then
        cf := greatest(1, sqrt(r.expected_days::numeric / least(cn, pn)));
        wpct := (cavg - pavg) / abs(pavg) * 100;
        wr := abs(wpct) / (r.threshold_pct * cf) / tmul;
        if wr >= 1 then
          wsev := case when wr >= 3 then 'high' when wr >= 1.5 then 'medium' else 'low' end;
          if sev is null or (case wsev when 'high' then 3 when 'medium' then 2 else 1 end) > (case sev when 'high' then 3 when 'medium' then 2 when 'low' then 1 else 0 end) then
            sev := wsev; prev := round(pavg, 2); cur := round(cavg, 2); ch := cavg - pavg; pct := wpct; z := null;
            ttl := format('%s เฉลี่ยสัปดาห์นี้ %s %s %s%% จากสัปดาห์ก่อน %s %s', r.name_th, round(cavg, r.decimals), case when wpct > 0 then 'ขึ้น' else 'ลดลง' end, round(abs(wpct), 1), round(pavg, r.decimals), r.unit);
            chk := chk || jsonb_build_object('rule', 'weekly', 'ratio', round(wr, 2), 'threshold_pct', r.threshold_pct, 'trust_multiplier', tmul,
                     'coverage_factor', round(cf, 3), 'expected_days', r.expected_days, 'effective_threshold_pct', round(r.threshold_pct * cf * tmul, 2),
                     'cur_avg', round(cavg, 4), 'prev_avg', round(pavg, 4), 'days_cur', cn, 'days_prev', pn, 'pct', round(wpct, 2),
                     'cur_from', cur_d - 6, 'cur_to', cur_d, 'prev_from', cur_d - 13, 'prev_to', cur_d - 7);
          end if;
        end if;
      end if;
    end if;
    if sev is not null and dem and sev = 'high' then sev := 'medium'; chk := chk || '{"capped":"demo"}'::jsonb; end if;
    family_id := r.family_id; metric_id := r.id; severity := sev; title := ttl; prev_value := prev; new_value := cur;
    change_abs := ch; change_pct := pct; is_demo := dem; checks := chk; has_obs := true;
    return next;
  end loop;
end $$;


--
-- Name: detect_received_signals(date); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.detect_received_signals(_d date) RETURNS integer
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE r record; c record; n integer := 0;
BEGIN
  FOR r IN
    SELECT DISTINCT ON (o.metric_id) o.metric_id, o.observed_on, o.received_at, o.effective_from, o.evidence_id,
      m.late_window_days AS allowed_days
    FROM public.observations o JOIN public.metrics m ON m.id = o.metric_id
    WHERE o.is_demo = false
      AND o.received_at >= (_d::timestamp at time zone 'Asia/Bangkok')
      AND o.received_at < ((_d + 1)::timestamp at time zone 'Asia/Bangkok')
      AND o.observed_on < _d
      AND (m.threshold_abs IS NOT NULL OR m.threshold_pct IS NOT NULL OR m.bands IS NOT NULL OR m.kind = 'release')
    ORDER BY o.metric_id, o.observed_on DESC
  LOOP
    IF _d - r.observed_on > r.allowed_days THEN CONTINUE; END IF;
    SELECT * INTO c FROM public.detect_core(r.observed_on, r.received_at)
      WHERE metric_id = r.metric_id AND severity IS NOT NULL AND is_demo = false;
    IF NOT FOUND THEN CONTINUE; END IF;
    -- One row per metric/day: a same-day signal is only replaced when the late one is more severe.
    INSERT INTO public.signals (family_id, metric_id, signal_date, severity, title, prev_value, new_value, change_abs, change_pct, is_demo, checks)
    VALUES (c.family_id, c.metric_id, _d, c.severity, c.title, c.prev_value, c.new_value, c.change_abs, c.change_pct, false,
      c.checks || jsonb_build_object('data_date', r.observed_on, 'received_at', r.received_at,
         'effective_from', r.effective_from, 'evidence_id', r.evidence_id,
         'arrival_day', _d, 'arrival_lag_days', _d - r.observed_on, 'late_window_days', r.allowed_days,
         'arrival_rule', 'late_above_threshold'))
    ON CONFLICT (metric_id, signal_date) DO UPDATE SET
      severity = EXCLUDED.severity, title = EXCLUDED.title, prev_value = EXCLUDED.prev_value,
      new_value = EXCLUDED.new_value, change_abs = EXCLUDED.change_abs, change_pct = EXCLUDED.change_pct,
      is_demo = false, checks = EXCLUDED.checks
    WHERE (CASE EXCLUDED.severity WHEN 'high' THEN 3 WHEN 'medium' THEN 2 ELSE 1 END) >
      (CASE signals.severity WHEN 'high' THEN 3 WHEN 'medium' THEN 2 ELSE 1 END)
      OR (signals.checks->>'arrival_rule' = 'late_above_threshold' AND signals.checks IS DISTINCT FROM EXCLUDED.checks
          AND signals.severity = EXCLUDED.severity);
    IF FOUND THEN n := n + 1; END IF;
  END LOOP;
  RETURN n;
END $$;


--
-- Name: detect_signals(date); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.detect_signals(_d date) RETURNS integer
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE c record; n integer := 0;
BEGIN
  FOR c IN SELECT * FROM public.detect_core(_d, NULL) LOOP
    IF c.severity IS NULL THEN
      DELETE FROM public.signals WHERE metric_id = c.metric_id AND signal_date = _d
        AND coalesce(checks->>'arrival_rule', '') <> 'late_above_threshold';
    ELSE
      INSERT INTO public.signals (family_id, metric_id, signal_date, severity, title, prev_value, new_value, change_abs, change_pct, is_demo, checks)
      VALUES (c.family_id, c.metric_id, _d, c.severity, c.title, c.prev_value, c.new_value, c.change_abs, c.change_pct, c.is_demo, c.checks)
      ON CONFLICT (metric_id, signal_date) DO UPDATE SET severity = EXCLUDED.severity, title = EXCLUDED.title,
        prev_value = EXCLUDED.prev_value, new_value = EXCLUDED.new_value, change_abs = EXCLUDED.change_abs,
        change_pct = EXCLUDED.change_pct, is_demo = EXCLUDED.is_demo, checks = EXCLUDED.checks
      WHERE coalesce(signals.checks->>'arrival_rule', '') <> 'late_above_threshold'
         OR (CASE EXCLUDED.severity WHEN 'high' THEN 3 WHEN 'medium' THEN 2 ELSE 1 END) >
            (CASE signals.severity WHEN 'high' THEN 3 WHEN 'medium' THEN 2 ELSE 1 END);
      n := n + 1;
    END IF;
  END LOOP;
  RETURN n;
END $$;


--
-- Name: family_evidence_source(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.family_evidence_source(_family text) RETURNS text
    LANGUAGE sql IMMUTABLE
    SET search_path TO 'public'
    AS $$
  select case _family
    when 'weather' then 'กรมอุตุฯ%' when 'air' then 'GISTDA%' when 'oil' then 'PTT%'
    when 'fx' then 'ExchangeRate%' when 'gold' then 'สมาคมค้าทองคำ%' when 'water' then '(ThaiWater|RID|กทม.|ปภ.)%'
    when 'food' then '(CheckRaka|กรมการค้าภายใน)%' when 'farm' then 'RakaKaset%' when 'traffic' then 'Longdo%'
    when 'lottery' then 'สำนักงานสลาก%' when 'utility' then 'การไฟฟ้า%' when 'rail' then 'รถไฟฟ้า%'
    else null end
$$;


--
-- Name: has_role(uuid, public.app_role); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;


--
-- Name: hit_rate_limit(text, integer); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.hit_rate_limit(_bucket text, _limit integer) RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE n integer; w timestamptz := date_trunc('minute', now());
BEGIN
  INSERT INTO api_rate_limits(bucket, window_start, hits) VALUES (_bucket, w, 1)
  ON CONFLICT (bucket, window_start) DO UPDATE SET hits = api_rate_limits.hits + 1
  RETURNING hits INTO n;
  IF random() < 0.01 THEN DELETE FROM api_rate_limits WHERE window_start < now() - interval '10 minutes'; END IF;
  RETURN n <= _limit;
END $$;


--
-- Name: prune_old_data(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.prune_old_data() RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
declare cut timestamptz := now() - interval '90 days'; r jsonb := '{}'::jsonb; n int;
begin
  update raw_evidence set job_id = null where job_id in (select id from ingest_jobs where status in ('done','failed') and created_at < cut);
  update raw_evidence set last_job_id = null where last_job_id in (select id from ingest_jobs where status in ('done','failed') and created_at < cut);
  delete from ingest_jobs where status in ('done','failed') and created_at < cut; get diagnostics n = row_count; r := r || jsonb_build_object('ingest_jobs', n);
  delete from source_run_history where ran_at < cut; get diagnostics n = row_count; r := r || jsonb_build_object('source_run_history', n);
  delete from station_snapshots where received_at < cut; get diagnostics n = row_count; r := r || jsonb_build_object('station_snapshots', n);
  delete from dam_readings where read_at < cut; get diagnostics n = row_count; r := r || jsonb_build_object('dam_readings', n);
  delete from news_items where published_at < cut; get diagnostics n = row_count; r := r || jsonb_build_object('news_items', n);
  delete from social_posts where posted_at < cut; get diagnostics n = row_count; r := r || jsonb_build_object('social_posts', n);
  delete from api_rate_limits where window_start < now() - interval '1 day'; get diagnostics n = row_count; r := r || jsonb_build_object('api_rate_limits', n);
  r := jsonb_build_object('ran_at', now(), 'deleted', r);
  insert into app_settings(key, value, updated_at) values ('prune_last', r::text, now())
    on conflict (key) do update set value = excluded.value, updated_at = now();
  return r;
end $$;


--
-- Name: rank_signals(date); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.rank_signals(_d date) RETURNS integer
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
declare n int; has_real boolean;
begin
  select exists(select 1 from signals where signal_date = _d and not is_demo) into has_real;
  with k as (
    select s.id, s.is_demo, f.reach,
      case s.severity when 'high' then 3 when 'medium' then 2 else 1 end::numeric as sw,
      least(2, greatest(1, coalesce((s.checks->>'z')::numeric / nullif((s.checks->>'vol_k')::numeric, 0), 1)))::numeric as zf,
      case f.trust when 'high' then 1.0 when 'medium' then 0.7 else 0.5 end::numeric as tf,
      case when exists (
        select 1 from raw_evidence e
        where e.source similar to family_evidence_source(s.family_id)
          and (e.fetched_at at time zone 'Asia/Bangkok')::date = _d
          and not exists (select 1 from raw_evidence p where p.url = e.url and p.sha256 = e.sha256 and p.fetched_at < e.fetched_at - interval '1 minute' and (p.fetched_at at time zone 'Asia/Bangkok')::date < _d)
          and exists (select 1 from raw_evidence p where p.url = e.url and p.fetched_at < e.fetched_at)
      ) then 1.0 else 0.8 end::numeric as ef
    from signals s join families f on f.id = s.family_id where s.signal_date = _d
  )
  update signals s set
    score = case when k.is_demo and has_real then 0 else round(k.sw * k.zf * k.tf * k.reach * k.ef, 3) end,
    checks = coalesce(s.checks, '{}'::jsonb) || jsonb_build_object('score', jsonb_build_object(
      'severity_weight', k.sw, 'z_factor', k.zf, 'trust_factor', k.tf, 'reach', k.reach, 'evidence_factor', k.ef,
      'demo_zeroed', k.is_demo and has_real,
      'total', case when k.is_demo and has_real then 0 else round(k.sw * k.zf * k.tf * k.reach * k.ef, 3) end))
  from k where k.id = s.id;
  get diagnostics n = row_count;
  return n;
end $$;


--
-- Name: record_signal_version(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.record_signal_version() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE s record; eid text; lv record; ev bigint[]; q text; kind text;
BEGIN
  s := CASE WHEN tg_op = 'DELETE' THEN old ELSE new END;
  eid := s.metric_id || ':' || s.signal_date;
  SELECT * INTO lv FROM signal_versions WHERE event_id = eid ORDER BY version DESC LIMIT 1;
  IF tg_op = 'DELETE' THEN
    IF lv.id IS NOT NULL AND lv.change_kind <> 'withdrawn' THEN
      INSERT INTO signal_versions (event_id, version, change_kind, severity, title, prev_value, new_value, prev_date, new_date, rules, evidence_ids, quality, reason)
      VALUES (eid, lv.version + 1, 'withdrawn', lv.severity, lv.title, lv.prev_value, lv.new_value, lv.prev_date, lv.new_date, lv.rules, lv.evidence_ids, lv.quality, 'ข้อมูลรอบใหม่ไม่ผ่านเกณฑ์แล้ว — ถอนสัญญาณ');
      UPDATE signal_events SET status = 'withdrawn', current_version = lv.version + 1, updated_at = now() WHERE event_id = eid;
    END IF;
    RETURN old;
  END IF;
  IF lv.id IS NOT NULL AND lv.change_kind <> 'withdrawn' AND lv.severity IS NOT DISTINCT FROM s.severity AND lv.title IS NOT DISTINCT FROM s.title
    AND lv.prev_value IS NOT DISTINCT FROM s.prev_value AND lv.new_value IS NOT DISTINCT FROM s.new_value THEN
    UPDATE signal_versions SET rules = s.checks WHERE id = lv.id;
    RETURN new;
  END IF;
  SELECT coalesce(array_agg(id), '{}') INTO ev FROM (
    SELECT id FROM raw_evidence WHERE source SIMILAR TO family_evidence_source(s.family_id)
      AND ((fetched_at AT TIME ZONE 'Asia/Bangkok')::date = s.signal_date
        OR id = (SELECT evidence_id FROM observations WHERE metric_id = s.metric_id
          AND observed_on = coalesce(nullif(s.checks->>'data_date', '')::date, s.signal_date)))
    ORDER BY id DESC LIMIT 15
  ) x;
  q := CASE WHEN s.is_demo THEN 'demo' WHEN cardinality(ev) > 0 THEN 'verified' ELSE 'cannot_verify' END;
  kind := CASE WHEN lv.id IS NULL THEN 'new' WHEN lv.change_kind = 'withdrawn' THEN 'reinstated' ELSE 'corrected' END;
  INSERT INTO signal_events (event_id, metric_id, family_id, event_type, signal_date, is_demo)
  VALUES (eid, s.metric_id, s.family_id, coalesce(s.checks->>'rule', 'delta'), s.signal_date, s.is_demo)
  ON CONFLICT (event_id) DO NOTHING;
  INSERT INTO signal_versions (event_id, version, change_kind, severity, title, prev_value, new_value, prev_date, new_date, rules, evidence_ids, quality, reason)
  VALUES (eid, coalesce(lv.version, 0) + 1, kind, s.severity, s.title, s.prev_value, s.new_value,
    nullif(s.checks->>'compared_with', '')::date, coalesce(nullif(s.checks->>'data_date', '')::date, s.signal_date), s.checks, ev, q,
    CASE kind WHEN 'new' THEN null WHEN 'reinstated' THEN 'กลับมาผ่านเกณฑ์อีกครั้ง' ELSE format('ค่าเปลี่ยนจาก %s เป็น %s', lv.new_value, s.new_value) END);
  UPDATE signal_events SET status = CASE WHEN kind = 'corrected' THEN 'corrected' ELSE 'active' END,
    current_version = coalesce(lv.version, 0) + 1, updated_at = now() WHERE event_id = eid;
  RETURN new;
END $$;


--
-- Name: refresh_metric_lag(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.refresh_metric_lag() RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
declare res jsonb := '{}'::jsonb; r record;
begin
  for r in
    with live as (
      select o.metric_id, ((o.received_at at time zone 'Asia/Bangkok')::date - o.observed_on) as lag
      from observations o
      where o.is_demo = false and o.received_at > now() - interval '60 days'
        and (o.metric_id, date_trunc('minute', o.received_at)) in (
          select metric_id, date_trunc('minute', received_at) from observations
          where received_at > now() - interval '60 days' group by 1, 2 having count(*) = 1)
    )
    select l.metric_id, count(*) n, ceil(percentile_cont(0.9) within group (order by greatest(l.lag, 0)))::int p90
    from live l join metrics m on m.id = l.metric_id where m.weekly group by l.metric_id
  loop
    if r.n >= 5 then
      update metrics set lag_days = least(greatest(r.p90, 1), 7) where id = r.metric_id;
      res := res || jsonb_build_object(r.metric_id, least(greatest(r.p90, 1), 7));
    end if;
  end loop;
  return res;
end $$;


--
-- Name: replay_signals(date); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.replay_signals(_d date) RETURNS TABLE(metric_id text, severity text, title text, prev_value numeric, new_value numeric, is_demo boolean)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  select c.metric_id, c.severity, c.title, c.prev_value, c.new_value, c.is_demo
  from detect_core(_d, ((_d + time '05:45') at time zone 'Asia/Bangkok')) c where c.severity is not null
$$;


--
-- Name: api_rate_limits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_rate_limits (
    bucket text NOT NULL,
    window_start timestamp with time zone NOT NULL,
    hits integer DEFAULT 0 NOT NULL
);


--
-- Name: app_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_settings (
    key text NOT NULL,
    value text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: brief_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.brief_images (
    id bigint NOT NULL,
    brief_date date NOT NULL,
    slot text NOT NULL,
    family_id text,
    storage_path text NOT NULL,
    prompt text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: brief_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.brief_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: brief_images_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.brief_images_id_seq OWNED BY public.brief_images.id;


--
-- Name: brief_updates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.brief_updates (
    id bigint NOT NULL,
    brief_date date NOT NULL,
    kind text NOT NULL,
    title text NOT NULL,
    body text,
    event_id text,
    version integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: brief_updates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.brief_updates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: brief_updates_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.brief_updates_id_seq OWNED BY public.brief_updates.id;


--
-- Name: daily_briefs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_briefs (
    brief_date date NOT NULL,
    body text NOT NULL,
    generated_at timestamp with time zone DEFAULT now() NOT NULL,
    signature text DEFAULT ''::text NOT NULL,
    items jsonb,
    published_at timestamp with time zone,
    cutoff_at timestamp with time zone,
    edition integer DEFAULT 1 NOT NULL,
    completeness jsonb,
    data_window jsonb
);


--
-- Name: dam_readings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dam_readings (
    id bigint NOT NULL,
    metric_id text NOT NULL,
    value numeric NOT NULL,
    observed_on date NOT NULL,
    read_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: dam_readings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dam_readings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: dam_readings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dam_readings_id_seq OWNED BY public.dam_readings.id;


--
-- Name: families; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.families (
    id text NOT NULL,
    name_th text NOT NULL,
    emoji text NOT NULL,
    description text NOT NULL,
    cadence text NOT NULL,
    is_live boolean DEFAULT false NOT NULL,
    source_name text NOT NULL,
    source_url text,
    sort integer DEFAULT 0 NOT NULL,
    trust text DEFAULT 'high'::text NOT NULL,
    reach numeric DEFAULT 1 NOT NULL
);


--
-- Name: holidays; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.holidays (
    id bigint NOT NULL,
    holiday_date date NOT NULL,
    name text NOT NULL,
    kind text NOT NULL,
    note text,
    delete_hash text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_gov boolean DEFAULT false NOT NULL,
    is_bank boolean DEFAULT false NOT NULL,
    source text DEFAULT 'user'::text NOT NULL,
    source_url text,
    CONSTRAINT holidays_name_check CHECK (((char_length(name) >= 2) AND (char_length(name) <= 120))),
    CONSTRAINT holidays_note_check CHECK (((note IS NULL) OR (char_length(note) <= 300)))
);


--
-- Name: holidays_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.holidays_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: holidays_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.holidays_id_seq OWNED BY public.holidays.id;


--
-- Name: ingest_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ingest_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ingest_jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ingest_jobs_id_seq OWNED BY public.ingest_jobs.id;


--
-- Name: job_locks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_locks (
    name text NOT NULL,
    locked_until timestamp with time zone NOT NULL
);


--
-- Name: lottery_draws; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lottery_draws (
    draw_date date NOT NULL,
    first text NOT NULL,
    last2 text,
    front3 text[],
    back3 text[],
    pdf_url text,
    video_url text,
    verified boolean DEFAULT false NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: metrics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.metrics (
    id text NOT NULL,
    family_id text NOT NULL,
    name_th text NOT NULL,
    unit text DEFAULT ''::text NOT NULL,
    kind text DEFAULT 'delta'::text NOT NULL,
    threshold_abs numeric,
    threshold_pct numeric,
    bands numeric[],
    decimals integer DEFAULT 2 NOT NULL,
    sort integer DEFAULT 0 NOT NULL,
    min_pct numeric,
    max_gap_days integer DEFAULT 7 NOT NULL,
    vol_k numeric DEFAULT 2 NOT NULL,
    weekly boolean DEFAULT false NOT NULL,
    lag_days integer DEFAULT 0 NOT NULL,
    expected_days integer DEFAULT 7 NOT NULL,
    late_window_days integer DEFAULT 2 NOT NULL
);


--
-- Name: COLUMN metrics.lag_days; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.metrics.lag_days IS 'Days a published value may trail the brief date (from real arrival times, refresh_metric_lag)';


--
-- Name: COLUMN metrics.expected_days; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.metrics.expected_days IS 'Readings expected per 7 days (5 = weekday agency); sparse weeks raise the weekly threshold';


--
-- Name: COLUMN metrics.late_window_days; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.metrics.late_window_days IS 'Days after the data date a late-arriving reading may still create a signal on its arrival day';


--
-- Name: news_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news_items (
    id bigint NOT NULL,
    source text NOT NULL,
    title text NOT NULL,
    link text NOT NULL,
    published_at timestamp with time zone NOT NULL,
    agency text,
    family_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    kind text DEFAULT 'tagged'::text NOT NULL
);


--
-- Name: news_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.news_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: news_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.news_items_id_seq OWNED BY public.news_items.id;


--
-- Name: observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.observations (
    id bigint NOT NULL,
    metric_id text NOT NULL,
    observed_on date NOT NULL,
    value numeric NOT NULL,
    is_demo boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    period_start date,
    period_end date,
    published_at timestamp with time zone,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    effective_from date,
    evidence_id bigint
);


--
-- Name: COLUMN observations.observed_on; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.observations.observed_on IS 'Date the value refers to (= period_end)';


--
-- Name: observations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.observations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: observations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.observations_id_seq OWNED BY public.observations.id;


--
-- Name: raw_evidence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.raw_evidence (
    id bigint NOT NULL,
    job_id bigint,
    source text NOT NULL,
    url text NOT NULL,
    http_status integer,
    content_type text,
    bytes integer DEFAULT 0 NOT NULL,
    sha256 text NOT NULL,
    storage_path text NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen_at timestamp with time zone,
    seen_count integer DEFAULT 1 NOT NULL,
    last_job_id bigint
);


--
-- Name: raw_evidence_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.raw_evidence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: raw_evidence_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.raw_evidence_id_seq OWNED BY public.raw_evidence.id;


--
-- Name: release_calendar; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.release_calendar (
    id bigint NOT NULL,
    family_id text NOT NULL,
    title text NOT NULL,
    release_date date NOT NULL
);


--
-- Name: release_calendar_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.release_calendar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: release_calendar_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.release_calendar_id_seq OWNED BY public.release_calendar.id;


--
-- Name: signal_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.signal_events (
    event_id text NOT NULL,
    metric_id text NOT NULL,
    family_id text NOT NULL,
    event_type text NOT NULL,
    area text DEFAULT 'ประเทศไทย'::text NOT NULL,
    signal_date date NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    current_version integer DEFAULT 1 NOT NULL,
    is_demo boolean DEFAULT false NOT NULL,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: signal_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.signal_versions (
    id bigint NOT NULL,
    event_id text NOT NULL,
    version integer NOT NULL,
    change_kind text NOT NULL,
    severity text,
    title text,
    prev_value numeric,
    new_value numeric,
    prev_date date,
    new_date date,
    rules jsonb,
    evidence_ids bigint[] DEFAULT '{}'::bigint[] NOT NULL,
    impact jsonb,
    advice text,
    quality text NOT NULL,
    reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: signal_versions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.signal_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: signal_versions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.signal_versions_id_seq OWNED BY public.signal_versions.id;


--
-- Name: signals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.signals (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    family_id text NOT NULL,
    metric_id text NOT NULL,
    signal_date date NOT NULL,
    severity text NOT NULL,
    title text NOT NULL,
    prev_value numeric,
    new_value numeric NOT NULL,
    change_abs numeric,
    change_pct numeric,
    is_demo boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    checks jsonb,
    score numeric
);


--
-- Name: social_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.social_posts (
    id bigint NOT NULL,
    post_id text NOT NULL,
    source text NOT NULL,
    posted_at timestamp with time zone NOT NULL,
    text text NOT NULL,
    url text NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    is_bkk boolean,
    area text,
    summary text,
    ai_reason text,
    evidence_id bigint,
    rail_status text,
    rail_reason text,
    rail_day date
);


--
-- Name: social_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.social_posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: social_posts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.social_posts_id_seq OWNED BY public.social_posts.id;


--
-- Name: source_breaker; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_breaker (
    source text NOT NULL,
    fail_streak integer DEFAULT 0 NOT NULL,
    open_until timestamp with time zone,
    probe boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: source_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_config (
    source text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    schedule text DEFAULT 'default'::text NOT NULL,
    daily_hour integer,
    fetch_mode text DEFAULT 'default'::text NOT NULL,
    max_attempts integer DEFAULT 3 NOT NULL,
    retry_delay_min integer,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    range_start integer,
    range_end integer,
    extra_hours integer[] DEFAULT '{}'::integer[] NOT NULL,
    custom_times text[] DEFAULT '{}'::text[] NOT NULL,
    CONSTRAINT source_config_daily_hour_check CHECK (((daily_hour >= 0) AND (daily_hour <= 23))),
    CONSTRAINT source_config_fetch_mode_check CHECK ((fetch_mode = ANY (ARRAY['default'::text, 'auto'::text, 'direct'::text, 'firecrawl'::text]))),
    CONSTRAINT source_config_max_attempts_check CHECK (((max_attempts >= 1) AND (max_attempts <= 6))),
    CONSTRAINT source_config_range_check CHECK ((((range_start IS NULL) OR ((range_start >= 0) AND (range_start <= 23))) AND ((range_end IS NULL) OR ((range_end >= 0) AND (range_end <= 23))))),
    CONSTRAINT source_config_retry_delay_min_check CHECK (((retry_delay_min >= 1) AND (retry_delay_min <= 240))),
    CONSTRAINT source_config_schedule_check CHECK ((schedule = ANY (ARRAY['default'::text, 'hourly'::text, '3h'::text, 'daily'::text, 'manual'::text, 'hourly_range'::text])))
);


--
-- Name: source_perf_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_perf_daily (
    source text NOT NULL,
    day date NOT NULL,
    runs integer DEFAULT 0 NOT NULL,
    ok integer DEFAULT 0 NOT NULL,
    causes jsonb DEFAULT '{}'::jsonb NOT NULL,
    files_changed integer DEFAULT 0 NOT NULL,
    median_data_age_min numeric
);


--
-- Name: source_registry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_registry (
    source text NOT NULL,
    owner text NOT NULL,
    channel text NOT NULL,
    licence text DEFAULT 'ไม่ระบุ'::text NOT NULL,
    cadence text NOT NULL,
    unit text DEFAULT ''::text NOT NULL,
    area text DEFAULT 'ประเทศไทย'::text NOT NULL,
    stale_after_days integer DEFAULT 1 NOT NULL,
    url text,
    sort integer DEFAULT 0 NOT NULL
);


--
-- Name: TABLE source_registry; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.source_registry IS 'Public provenance and cadence for agency data sources; freshness is evaluated from observation dates, not page refresh dates.';


--
-- Name: source_run_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_run_history (
    id bigint NOT NULL,
    source text NOT NULL,
    ran_at timestamp with time zone DEFAULT now() NOT NULL,
    ok boolean NOT NULL,
    rows integer DEFAULT 0 NOT NULL,
    error text,
    run_kind text DEFAULT 'hourly'::text NOT NULL
);


--
-- Name: source_run_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.source_run_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: source_run_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.source_run_history_id_seq OWNED BY public.source_run_history.id;


--
-- Name: source_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_runs (
    source text NOT NULL,
    ran_at timestamp with time zone DEFAULT now() NOT NULL,
    ok boolean NOT NULL,
    rows integer DEFAULT 0 NOT NULL,
    error text,
    last_ok_at timestamp with time zone,
    url text,
    kind text DEFAULT 'api'::text NOT NULL,
    sample text,
    run_kind text DEFAULT 'hourly'::text NOT NULL
);


--
-- Name: station_locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.station_locations (
    source text NOT NULL,
    station_id text NOT NULL,
    name text NOT NULL,
    lat numeric NOT NULL,
    lng numeric NOT NULL,
    method text DEFAULT 'source'::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT station_locations_method_check CHECK ((method = ANY (ARRAY['source'::text, 'geocoded'::text])))
);


--
-- Name: station_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.station_snapshots (
    id bigint NOT NULL,
    source text NOT NULL,
    station_id text NOT NULL,
    name text NOT NULL,
    area text,
    value numeric,
    pct numeric,
    status text,
    observed_at timestamp with time zone,
    evidence_id bigint,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    lat numeric,
    lng numeric
);


--
-- Name: station_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.station_snapshots ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.station_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tax_deadlines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tax_deadlines (
    id bigint NOT NULL,
    due_date date NOT NULL,
    channel text NOT NULL,
    items text[] DEFAULT '{}'::text[] NOT NULL,
    source_url text NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: tax_deadlines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tax_deadlines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tax_deadlines_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tax_deadlines_id_seq OWNED BY public.tax_deadlines.id;


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    role public.app_role NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: weather_station_obs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.weather_station_obs (
    id bigint NOT NULL,
    station_id text NOT NULL,
    name text NOT NULL,
    kind text NOT NULL,
    obs_date date NOT NULL,
    obs_time text,
    temp numeric,
    tmin numeric,
    rain24 numeric,
    rain_pct numeric,
    descr text,
    dist_km numeric,
    source_url text NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT weather_station_obs_kind_check CHECK ((kind = ANY (ARRAY['3h'::text, '7d'::text])))
);


--
-- Name: weather_station_obs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.weather_station_obs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: weather_station_obs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.weather_station_obs_id_seq OWNED BY public.weather_station_obs.id;


--
-- Name: brief_images id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.brief_images ALTER COLUMN id SET DEFAULT nextval('public.brief_images_id_seq'::regclass);


--
-- Name: brief_updates id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.brief_updates ALTER COLUMN id SET DEFAULT nextval('public.brief_updates_id_seq'::regclass);


--
-- Name: dam_readings id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dam_readings ALTER COLUMN id SET DEFAULT nextval('public.dam_readings_id_seq'::regclass);


--
-- Name: holidays id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holidays ALTER COLUMN id SET DEFAULT nextval('public.holidays_id_seq'::regclass);


--
-- Name: ingest_jobs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingest_jobs ALTER COLUMN id SET DEFAULT nextval('public.ingest_jobs_id_seq'::regclass);


--
-- Name: news_items id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_items ALTER COLUMN id SET DEFAULT nextval('public.news_items_id_seq'::regclass);


--
-- Name: observations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observations ALTER COLUMN id SET DEFAULT nextval('public.observations_id_seq'::regclass);


--
-- Name: raw_evidence id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_evidence ALTER COLUMN id SET DEFAULT nextval('public.raw_evidence_id_seq'::regclass);


--
-- Name: release_calendar id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.release_calendar ALTER COLUMN id SET DEFAULT nextval('public.release_calendar_id_seq'::regclass);


--
-- Name: signal_versions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_versions ALTER COLUMN id SET DEFAULT nextval('public.signal_versions_id_seq'::regclass);


--
-- Name: social_posts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_posts ALTER COLUMN id SET DEFAULT nextval('public.social_posts_id_seq'::regclass);


--
-- Name: source_run_history id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_run_history ALTER COLUMN id SET DEFAULT nextval('public.source_run_history_id_seq'::regclass);


--
-- Name: tax_deadlines id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_deadlines ALTER COLUMN id SET DEFAULT nextval('public.tax_deadlines_id_seq'::regclass);


--
-- Name: weather_station_obs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weather_station_obs ALTER COLUMN id SET DEFAULT nextval('public.weather_station_obs_id_seq'::regclass);


--
-- Name: api_rate_limits api_rate_limits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_rate_limits
    ADD CONSTRAINT api_rate_limits_pkey PRIMARY KEY (bucket, window_start);


--
-- Name: app_settings app_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_settings
    ADD CONSTRAINT app_settings_pkey PRIMARY KEY (key);


--
-- Name: brief_images brief_images_brief_date_slot_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.brief_images
    ADD CONSTRAINT brief_images_brief_date_slot_key UNIQUE (brief_date, slot);


--
-- Name: brief_images brief_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.brief_images
    ADD CONSTRAINT brief_images_pkey PRIMARY KEY (id);


--
-- Name: brief_updates brief_updates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.brief_updates
    ADD CONSTRAINT brief_updates_pkey PRIMARY KEY (id);


--
-- Name: daily_briefs daily_briefs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_briefs
    ADD CONSTRAINT daily_briefs_pkey PRIMARY KEY (brief_date);


--
-- Name: dam_readings dam_readings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dam_readings
    ADD CONSTRAINT dam_readings_pkey PRIMARY KEY (id);


--
-- Name: families families_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.families
    ADD CONSTRAINT families_pkey PRIMARY KEY (id);


--
-- Name: holidays holidays_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holidays
    ADD CONSTRAINT holidays_pkey PRIMARY KEY (id);


--
-- Name: ingest_jobs ingest_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingest_jobs
    ADD CONSTRAINT ingest_jobs_pkey PRIMARY KEY (id);


--
-- Name: job_locks job_locks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_locks
    ADD CONSTRAINT job_locks_pkey PRIMARY KEY (name);


--
-- Name: lottery_draws lottery_draws_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lottery_draws
    ADD CONSTRAINT lottery_draws_pkey PRIMARY KEY (draw_date);


--
-- Name: metrics metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT metrics_pkey PRIMARY KEY (id);


--
-- Name: news_items news_items_link_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_items
    ADD CONSTRAINT news_items_link_key UNIQUE (link);


--
-- Name: news_items news_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_items
    ADD CONSTRAINT news_items_pkey PRIMARY KEY (id);


--
-- Name: observations observations_metric_id_observed_on_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT observations_metric_id_observed_on_key UNIQUE (metric_id, observed_on);


--
-- Name: observations observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT observations_pkey PRIMARY KEY (id);


--
-- Name: raw_evidence raw_evidence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_evidence
    ADD CONSTRAINT raw_evidence_pkey PRIMARY KEY (id);


--
-- Name: release_calendar release_calendar_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.release_calendar
    ADD CONSTRAINT release_calendar_pkey PRIMARY KEY (id);


--
-- Name: signal_events signal_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_events
    ADD CONSTRAINT signal_events_pkey PRIMARY KEY (event_id);


--
-- Name: signal_versions signal_versions_event_id_version_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_versions
    ADD CONSTRAINT signal_versions_event_id_version_key UNIQUE (event_id, version);


--
-- Name: signal_versions signal_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_versions
    ADD CONSTRAINT signal_versions_pkey PRIMARY KEY (id);


--
-- Name: signals signals_metric_id_signal_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signals
    ADD CONSTRAINT signals_metric_id_signal_date_key UNIQUE (metric_id, signal_date);


--
-- Name: signals signals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signals
    ADD CONSTRAINT signals_pkey PRIMARY KEY (id);


--
-- Name: social_posts social_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_posts
    ADD CONSTRAINT social_posts_pkey PRIMARY KEY (id);


--
-- Name: social_posts social_posts_post_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_posts
    ADD CONSTRAINT social_posts_post_id_key UNIQUE (post_id);


--
-- Name: source_breaker source_breaker_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_breaker
    ADD CONSTRAINT source_breaker_pkey PRIMARY KEY (source);


--
-- Name: source_config source_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_config
    ADD CONSTRAINT source_config_pkey PRIMARY KEY (source);


--
-- Name: source_perf_daily source_perf_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_perf_daily
    ADD CONSTRAINT source_perf_daily_pkey PRIMARY KEY (source, day);


--
-- Name: source_registry source_registry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_registry
    ADD CONSTRAINT source_registry_pkey PRIMARY KEY (source);


--
-- Name: source_run_history source_run_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_run_history
    ADD CONSTRAINT source_run_history_pkey PRIMARY KEY (id);


--
-- Name: source_runs source_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_runs
    ADD CONSTRAINT source_runs_pkey PRIMARY KEY (source);


--
-- Name: station_locations station_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.station_locations
    ADD CONSTRAINT station_locations_pkey PRIMARY KEY (source, station_id);


--
-- Name: station_snapshots station_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.station_snapshots
    ADD CONSTRAINT station_snapshots_pkey PRIMARY KEY (id);


--
-- Name: tax_deadlines tax_deadlines_due_date_channel_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_deadlines
    ADD CONSTRAINT tax_deadlines_due_date_channel_key UNIQUE (due_date, channel);


--
-- Name: tax_deadlines tax_deadlines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_deadlines
    ADD CONSTRAINT tax_deadlines_pkey PRIMARY KEY (id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);


--
-- Name: user_roles user_roles_user_id_role_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);


--
-- Name: weather_station_obs weather_station_obs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weather_station_obs
    ADD CONSTRAINT weather_station_obs_pkey PRIMARY KEY (id);


--
-- Name: weather_station_obs weather_station_obs_station_id_obs_date_kind_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weather_station_obs
    ADD CONSTRAINT weather_station_obs_station_id_obs_date_kind_key UNIQUE (station_id, obs_date, kind);


--
-- Name: dam_readings_read_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX dam_readings_read_at ON public.dam_readings USING btree (read_at DESC);


--
-- Name: holidays_date_name_uq; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX holidays_date_name_uq ON public.holidays USING btree (holiday_date, name);


--
-- Name: ingest_jobs_batch_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ingest_jobs_batch_idx ON public.ingest_jobs USING btree (batch_id);


--
-- Name: ingest_jobs_due_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ingest_jobs_due_idx ON public.ingest_jobs USING btree (status, run_after);


--
-- Name: news_items_family_id_published_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX news_items_family_id_published_at_idx ON public.news_items USING btree (family_id, published_at DESC);


--
-- Name: news_items_kind_pub_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX news_items_kind_pub_idx ON public.news_items USING btree (kind, published_at DESC);


--
-- Name: news_items_published_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX news_items_published_at_idx ON public.news_items USING btree (published_at DESC);


--
-- Name: observations_metric_id_observed_on_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX observations_metric_id_observed_on_idx ON public.observations USING btree (metric_id, observed_on DESC);


--
-- Name: raw_evidence_last_job_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX raw_evidence_last_job_idx ON public.raw_evidence USING btree (last_job_id);


--
-- Name: raw_evidence_sha_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX raw_evidence_sha_idx ON public.raw_evidence USING btree (sha256);


--
-- Name: raw_evidence_source_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX raw_evidence_source_idx ON public.raw_evidence USING btree (source, fetched_at DESC);


--
-- Name: raw_evidence_url_fetched_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX raw_evidence_url_fetched_idx ON public.raw_evidence USING btree (url, fetched_at DESC);


--
-- Name: raw_evidence_url_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX raw_evidence_url_idx ON public.raw_evidence USING btree (url, fetched_at);


--
-- Name: signals_signal_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX signals_signal_date_idx ON public.signals USING btree (signal_date DESC);


--
-- Name: social_posts_posted_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX social_posts_posted_idx ON public.social_posts USING btree (posted_at DESC);


--
-- Name: social_posts_rail_day_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX social_posts_rail_day_idx ON public.social_posts USING btree (source, rail_day);


--
-- Name: source_run_history_ran_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX source_run_history_ran_at_idx ON public.source_run_history USING btree (ran_at DESC);


--
-- Name: station_snapshots_src_recv; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX station_snapshots_src_recv ON public.station_snapshots USING btree (source, received_at DESC);


--
-- Name: signals signals_versioning; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER signals_versioning AFTER INSERT OR DELETE OR UPDATE ON public.signals FOR EACH ROW EXECUTE FUNCTION public.record_signal_version();


--
-- Name: dam_readings dam_readings_metric_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dam_readings
    ADD CONSTRAINT dam_readings_metric_id_fkey FOREIGN KEY (metric_id) REFERENCES public.metrics(id) ON DELETE CASCADE;


--
-- Name: metrics metrics_family_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT metrics_family_id_fkey FOREIGN KEY (family_id) REFERENCES public.families(id) ON DELETE CASCADE;


--
-- Name: news_items news_items_family_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_items
    ADD CONSTRAINT news_items_family_id_fkey FOREIGN KEY (family_id) REFERENCES public.families(id) ON DELETE SET NULL;


--
-- Name: observations observations_evidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT observations_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES public.raw_evidence(id) ON DELETE SET NULL;


--
-- Name: observations observations_metric_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT observations_metric_id_fkey FOREIGN KEY (metric_id) REFERENCES public.metrics(id) ON DELETE CASCADE;


--
-- Name: raw_evidence raw_evidence_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_evidence
    ADD CONSTRAINT raw_evidence_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.ingest_jobs(id) ON DELETE SET NULL;


--
-- Name: release_calendar release_calendar_family_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.release_calendar
    ADD CONSTRAINT release_calendar_family_id_fkey FOREIGN KEY (family_id) REFERENCES public.families(id) ON DELETE CASCADE;


--
-- Name: signal_events signal_events_family_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_events
    ADD CONSTRAINT signal_events_family_id_fkey FOREIGN KEY (family_id) REFERENCES public.families(id);


--
-- Name: signal_events signal_events_metric_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_events
    ADD CONSTRAINT signal_events_metric_id_fkey FOREIGN KEY (metric_id) REFERENCES public.metrics(id);


--
-- Name: signal_versions signal_versions_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_versions
    ADD CONSTRAINT signal_versions_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.signal_events(event_id) ON DELETE CASCADE;


--
-- Name: signals signals_family_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signals
    ADD CONSTRAINT signals_family_id_fkey FOREIGN KEY (family_id) REFERENCES public.families(id) ON DELETE CASCADE;


--
-- Name: signals signals_metric_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signals
    ADD CONSTRAINT signals_metric_id_fkey FOREIGN KEY (metric_id) REFERENCES public.metrics(id) ON DELETE CASCADE;


--
-- Name: social_posts social_posts_evidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_posts
    ADD CONSTRAINT social_posts_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES public.raw_evidence(id) ON DELETE SET NULL;


--
-- Name: station_snapshots station_snapshots_evidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.station_snapshots
    ADD CONSTRAINT station_snapshots_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES public.raw_evidence(id);


--
-- Name: source_config Admins read source config; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Admins read source config" ON public.source_config FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: station_locations Public read station locations; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public read station locations" ON public.station_locations FOR SELECT TO authenticated, anon USING (true);


--
-- Name: source_perf_daily admin read perf; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin read perf" ON public.source_perf_daily FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: source_breaker admins read breaker; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admins read breaker" ON public.source_breaker FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));


--
-- Name: api_rate_limits; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.api_rate_limits ENABLE ROW LEVEL SECURITY;

--
-- Name: app_settings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

--
-- Name: brief_images; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.brief_images ENABLE ROW LEVEL SECURITY;

--
-- Name: brief_updates; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.brief_updates ENABLE ROW LEVEL SECURITY;

--
-- Name: daily_briefs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.daily_briefs ENABLE ROW LEVEL SECURITY;

--
-- Name: dam_readings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.dam_readings ENABLE ROW LEVEL SECURITY;

--
-- Name: families; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.families ENABLE ROW LEVEL SECURITY;

--
-- Name: holidays; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.holidays ENABLE ROW LEVEL SECURITY;

--
-- Name: ingest_jobs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ingest_jobs ENABLE ROW LEVEL SECURITY;

--
-- Name: job_locks; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.job_locks ENABLE ROW LEVEL SECURITY;

--
-- Name: lottery_draws; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.lottery_draws ENABLE ROW LEVEL SECURITY;

--
-- Name: metrics; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.metrics ENABLE ROW LEVEL SECURITY;

--
-- Name: news_items; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.news_items ENABLE ROW LEVEL SECURITY;

--
-- Name: observations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.observations ENABLE ROW LEVEL SECURITY;

--
-- Name: brief_updates public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.brief_updates FOR SELECT TO authenticated, anon USING (true);


--
-- Name: daily_briefs public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.daily_briefs FOR SELECT TO authenticated, anon USING (true);


--
-- Name: families public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.families FOR SELECT TO authenticated, anon USING (true);


--
-- Name: ingest_jobs public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.ingest_jobs FOR SELECT TO authenticated, anon USING (true);


--
-- Name: lottery_draws public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.lottery_draws FOR SELECT TO authenticated, anon USING (true);


--
-- Name: metrics public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.metrics FOR SELECT TO authenticated, anon USING (true);


--
-- Name: news_items public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.news_items FOR SELECT TO authenticated, anon USING (true);


--
-- Name: observations public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.observations FOR SELECT TO authenticated, anon USING (true);


--
-- Name: raw_evidence public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.raw_evidence FOR SELECT TO authenticated, anon USING (true);


--
-- Name: release_calendar public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.release_calendar FOR SELECT TO authenticated, anon USING (true);


--
-- Name: signal_events public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.signal_events FOR SELECT TO authenticated, anon USING (true);


--
-- Name: signal_versions public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.signal_versions FOR SELECT TO authenticated, anon USING (true);


--
-- Name: signals public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.signals FOR SELECT TO authenticated, anon USING (true);


--
-- Name: source_registry public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.source_registry FOR SELECT TO authenticated, anon USING (true);


--
-- Name: source_run_history public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.source_run_history FOR SELECT TO authenticated, anon USING (true);


--
-- Name: source_runs public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.source_runs FOR SELECT TO authenticated, anon USING (true);


--
-- Name: weather_station_obs public read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read" ON public.weather_station_obs FOR SELECT TO authenticated, anon USING (true);


--
-- Name: brief_images public read brief images; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read brief images" ON public.brief_images FOR SELECT TO authenticated, anon USING (true);


--
-- Name: dam_readings public read dam readings; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read dam readings" ON public.dam_readings FOR SELECT TO authenticated, anon USING (true);


--
-- Name: holidays public read holidays; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read holidays" ON public.holidays FOR SELECT TO authenticated, anon USING (true);


--
-- Name: app_settings public read settings; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read settings" ON public.app_settings FOR SELECT TO authenticated, anon USING (true);


--
-- Name: social_posts public read social; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read social" ON public.social_posts FOR SELECT TO authenticated, anon USING (true);


--
-- Name: station_snapshots public read station snapshots; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read station snapshots" ON public.station_snapshots FOR SELECT TO authenticated, anon USING (true);


--
-- Name: tax_deadlines public read tax deadlines; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read tax deadlines" ON public.tax_deadlines FOR SELECT TO authenticated, anon USING (true);


--
-- Name: raw_evidence; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.raw_evidence ENABLE ROW LEVEL SECURITY;

--
-- Name: release_calendar; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.release_calendar ENABLE ROW LEVEL SECURITY;

--
-- Name: signal_events; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.signal_events ENABLE ROW LEVEL SECURITY;

--
-- Name: signal_versions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.signal_versions ENABLE ROW LEVEL SECURITY;

--
-- Name: signals; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.signals ENABLE ROW LEVEL SECURITY;

--
-- Name: social_posts; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.social_posts ENABLE ROW LEVEL SECURITY;

--
-- Name: source_breaker; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.source_breaker ENABLE ROW LEVEL SECURITY;

--
-- Name: source_config; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.source_config ENABLE ROW LEVEL SECURITY;

--
-- Name: source_perf_daily; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.source_perf_daily ENABLE ROW LEVEL SECURITY;

--
-- Name: source_registry; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.source_registry ENABLE ROW LEVEL SECURITY;

--
-- Name: source_run_history; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.source_run_history ENABLE ROW LEVEL SECURITY;

--
-- Name: source_runs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.source_runs ENABLE ROW LEVEL SECURITY;

--
-- Name: station_locations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.station_locations ENABLE ROW LEVEL SECURITY;

--
-- Name: station_snapshots; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.station_snapshots ENABLE ROW LEVEL SECURITY;

--
-- Name: tax_deadlines; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.tax_deadlines ENABLE ROW LEVEL SECURITY;

--
-- Name: user_roles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

--
-- Name: user_roles users read own roles; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "users read own roles" ON public.user_roles FOR SELECT TO authenticated USING ((auth.uid() = user_id));


--
-- Name: weather_station_obs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.weather_station_obs ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;
GRANT USAGE ON SCHEMA public TO sandbox_exec;


--
-- Name: TABLE ingest_jobs; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.ingest_jobs TO anon;
GRANT ALL ON TABLE public.ingest_jobs TO authenticated;
GRANT ALL ON TABLE public.ingest_jobs TO service_role;
GRANT SELECT,INSERT ON TABLE public.ingest_jobs TO sandbox_exec;


--
-- Name: FUNCTION claim_ingest_job(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.claim_ingest_job() FROM PUBLIC;
GRANT ALL ON FUNCTION public.claim_ingest_job() TO service_role;


--
-- Name: FUNCTION detect_core(_d date, _cutoff timestamp with time zone); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.detect_core(_d date, _cutoff timestamp with time zone) TO anon;
GRANT ALL ON FUNCTION public.detect_core(_d date, _cutoff timestamp with time zone) TO authenticated;
GRANT ALL ON FUNCTION public.detect_core(_d date, _cutoff timestamp with time zone) TO service_role;


--
-- Name: FUNCTION detect_received_signals(_d date); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.detect_received_signals(_d date) FROM PUBLIC;
GRANT ALL ON FUNCTION public.detect_received_signals(_d date) TO service_role;


--
-- Name: FUNCTION detect_signals(_d date); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.detect_signals(_d date) FROM PUBLIC;
GRANT ALL ON FUNCTION public.detect_signals(_d date) TO service_role;


--
-- Name: FUNCTION family_evidence_source(_family text); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.family_evidence_source(_family text) TO anon;
GRANT ALL ON FUNCTION public.family_evidence_source(_family text) TO authenticated;
GRANT ALL ON FUNCTION public.family_evidence_source(_family text) TO service_role;


--
-- Name: FUNCTION has_role(_user_id uuid, _role public.app_role); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.has_role(_user_id uuid, _role public.app_role) FROM PUBLIC;
GRANT ALL ON FUNCTION public.has_role(_user_id uuid, _role public.app_role) TO authenticated;
GRANT ALL ON FUNCTION public.has_role(_user_id uuid, _role public.app_role) TO service_role;


--
-- Name: FUNCTION hit_rate_limit(_bucket text, _limit integer); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.hit_rate_limit(_bucket text, _limit integer) FROM PUBLIC;
GRANT ALL ON FUNCTION public.hit_rate_limit(_bucket text, _limit integer) TO service_role;


--
-- Name: FUNCTION prune_old_data(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.prune_old_data() FROM PUBLIC;
GRANT ALL ON FUNCTION public.prune_old_data() TO service_role;


--
-- Name: FUNCTION rank_signals(_d date); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.rank_signals(_d date) FROM PUBLIC;
GRANT ALL ON FUNCTION public.rank_signals(_d date) TO service_role;


--
-- Name: FUNCTION record_signal_version(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.record_signal_version() FROM PUBLIC;
GRANT ALL ON FUNCTION public.record_signal_version() TO service_role;


--
-- Name: FUNCTION refresh_metric_lag(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.refresh_metric_lag() FROM PUBLIC;
GRANT ALL ON FUNCTION public.refresh_metric_lag() TO service_role;


--
-- Name: FUNCTION replay_signals(_d date); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.replay_signals(_d date) TO anon;
GRANT ALL ON FUNCTION public.replay_signals(_d date) TO authenticated;
GRANT ALL ON FUNCTION public.replay_signals(_d date) TO service_role;


--
-- Name: TABLE api_rate_limits; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.api_rate_limits TO anon;
GRANT ALL ON TABLE public.api_rate_limits TO authenticated;
GRANT ALL ON TABLE public.api_rate_limits TO service_role;
GRANT SELECT,INSERT ON TABLE public.api_rate_limits TO sandbox_exec;


--
-- Name: TABLE app_settings; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.app_settings TO anon;
GRANT ALL ON TABLE public.app_settings TO authenticated;
GRANT ALL ON TABLE public.app_settings TO service_role;
GRANT SELECT,INSERT ON TABLE public.app_settings TO sandbox_exec;


--
-- Name: TABLE brief_images; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.brief_images TO anon;
GRANT ALL ON TABLE public.brief_images TO authenticated;
GRANT ALL ON TABLE public.brief_images TO service_role;
GRANT SELECT,INSERT ON TABLE public.brief_images TO sandbox_exec;


--
-- Name: SEQUENCE brief_images_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.brief_images_id_seq TO anon;
GRANT ALL ON SEQUENCE public.brief_images_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.brief_images_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.brief_images_id_seq TO sandbox_exec;


--
-- Name: TABLE brief_updates; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.brief_updates TO anon;
GRANT ALL ON TABLE public.brief_updates TO authenticated;
GRANT ALL ON TABLE public.brief_updates TO service_role;
GRANT SELECT,INSERT ON TABLE public.brief_updates TO sandbox_exec;


--
-- Name: SEQUENCE brief_updates_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.brief_updates_id_seq TO anon;
GRANT ALL ON SEQUENCE public.brief_updates_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.brief_updates_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.brief_updates_id_seq TO sandbox_exec;


--
-- Name: TABLE daily_briefs; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.daily_briefs TO anon;
GRANT ALL ON TABLE public.daily_briefs TO authenticated;
GRANT ALL ON TABLE public.daily_briefs TO service_role;
GRANT SELECT,INSERT ON TABLE public.daily_briefs TO sandbox_exec;


--
-- Name: TABLE dam_readings; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.dam_readings TO anon;
GRANT ALL ON TABLE public.dam_readings TO authenticated;
GRANT ALL ON TABLE public.dam_readings TO service_role;
GRANT SELECT,INSERT ON TABLE public.dam_readings TO sandbox_exec;


--
-- Name: SEQUENCE dam_readings_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.dam_readings_id_seq TO anon;
GRANT ALL ON SEQUENCE public.dam_readings_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.dam_readings_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.dam_readings_id_seq TO sandbox_exec;


--
-- Name: TABLE families; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.families TO anon;
GRANT ALL ON TABLE public.families TO authenticated;
GRANT ALL ON TABLE public.families TO service_role;
GRANT SELECT,INSERT ON TABLE public.families TO sandbox_exec;


--
-- Name: TABLE holidays; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.holidays TO anon;
GRANT ALL ON TABLE public.holidays TO authenticated;
GRANT ALL ON TABLE public.holidays TO service_role;
GRANT SELECT,INSERT ON TABLE public.holidays TO sandbox_exec;


--
-- Name: COLUMN holidays.id; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT(id) ON TABLE public.holidays TO anon;
GRANT SELECT(id) ON TABLE public.holidays TO authenticated;


--
-- Name: COLUMN holidays.holiday_date; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT(holiday_date) ON TABLE public.holidays TO anon;
GRANT SELECT(holiday_date) ON TABLE public.holidays TO authenticated;


--
-- Name: COLUMN holidays.name; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT(name) ON TABLE public.holidays TO anon;
GRANT SELECT(name) ON TABLE public.holidays TO authenticated;


--
-- Name: COLUMN holidays.kind; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT(kind) ON TABLE public.holidays TO anon;
GRANT SELECT(kind) ON TABLE public.holidays TO authenticated;


--
-- Name: COLUMN holidays.note; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT(note) ON TABLE public.holidays TO anon;
GRANT SELECT(note) ON TABLE public.holidays TO authenticated;


--
-- Name: COLUMN holidays.created_at; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT(created_at) ON TABLE public.holidays TO anon;
GRANT SELECT(created_at) ON TABLE public.holidays TO authenticated;


--
-- Name: SEQUENCE holidays_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.holidays_id_seq TO anon;
GRANT ALL ON SEQUENCE public.holidays_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.holidays_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.holidays_id_seq TO sandbox_exec;


--
-- Name: SEQUENCE ingest_jobs_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.ingest_jobs_id_seq TO anon;
GRANT ALL ON SEQUENCE public.ingest_jobs_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.ingest_jobs_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.ingest_jobs_id_seq TO sandbox_exec;


--
-- Name: TABLE job_locks; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.job_locks TO anon;
GRANT ALL ON TABLE public.job_locks TO authenticated;
GRANT ALL ON TABLE public.job_locks TO service_role;
GRANT SELECT,INSERT ON TABLE public.job_locks TO sandbox_exec;


--
-- Name: TABLE lottery_draws; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.lottery_draws TO anon;
GRANT ALL ON TABLE public.lottery_draws TO authenticated;
GRANT ALL ON TABLE public.lottery_draws TO service_role;
GRANT SELECT,INSERT ON TABLE public.lottery_draws TO sandbox_exec;


--
-- Name: TABLE metrics; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.metrics TO anon;
GRANT ALL ON TABLE public.metrics TO authenticated;
GRANT ALL ON TABLE public.metrics TO service_role;
GRANT SELECT,INSERT ON TABLE public.metrics TO sandbox_exec;


--
-- Name: TABLE news_items; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.news_items TO anon;
GRANT ALL ON TABLE public.news_items TO authenticated;
GRANT ALL ON TABLE public.news_items TO service_role;
GRANT SELECT,INSERT ON TABLE public.news_items TO sandbox_exec;


--
-- Name: SEQUENCE news_items_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.news_items_id_seq TO anon;
GRANT ALL ON SEQUENCE public.news_items_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.news_items_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.news_items_id_seq TO sandbox_exec;


--
-- Name: TABLE observations; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.observations TO anon;
GRANT ALL ON TABLE public.observations TO authenticated;
GRANT ALL ON TABLE public.observations TO service_role;
GRANT SELECT,INSERT ON TABLE public.observations TO sandbox_exec;


--
-- Name: SEQUENCE observations_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.observations_id_seq TO anon;
GRANT ALL ON SEQUENCE public.observations_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.observations_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.observations_id_seq TO sandbox_exec;


--
-- Name: TABLE raw_evidence; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.raw_evidence TO anon;
GRANT ALL ON TABLE public.raw_evidence TO authenticated;
GRANT ALL ON TABLE public.raw_evidence TO service_role;
GRANT SELECT,INSERT ON TABLE public.raw_evidence TO sandbox_exec;


--
-- Name: SEQUENCE raw_evidence_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.raw_evidence_id_seq TO anon;
GRANT ALL ON SEQUENCE public.raw_evidence_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.raw_evidence_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.raw_evidence_id_seq TO sandbox_exec;


--
-- Name: TABLE release_calendar; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.release_calendar TO anon;
GRANT ALL ON TABLE public.release_calendar TO authenticated;
GRANT ALL ON TABLE public.release_calendar TO service_role;
GRANT SELECT,INSERT ON TABLE public.release_calendar TO sandbox_exec;


--
-- Name: SEQUENCE release_calendar_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.release_calendar_id_seq TO anon;
GRANT ALL ON SEQUENCE public.release_calendar_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.release_calendar_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.release_calendar_id_seq TO sandbox_exec;


--
-- Name: TABLE signal_events; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.signal_events TO anon;
GRANT ALL ON TABLE public.signal_events TO authenticated;
GRANT ALL ON TABLE public.signal_events TO service_role;
GRANT SELECT,INSERT ON TABLE public.signal_events TO sandbox_exec;


--
-- Name: TABLE signal_versions; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.signal_versions TO anon;
GRANT ALL ON TABLE public.signal_versions TO authenticated;
GRANT ALL ON TABLE public.signal_versions TO service_role;
GRANT SELECT,INSERT ON TABLE public.signal_versions TO sandbox_exec;


--
-- Name: SEQUENCE signal_versions_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.signal_versions_id_seq TO anon;
GRANT ALL ON SEQUENCE public.signal_versions_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.signal_versions_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.signal_versions_id_seq TO sandbox_exec;


--
-- Name: TABLE signals; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.signals TO anon;
GRANT ALL ON TABLE public.signals TO authenticated;
GRANT ALL ON TABLE public.signals TO service_role;
GRANT SELECT,INSERT ON TABLE public.signals TO sandbox_exec;


--
-- Name: TABLE social_posts; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.social_posts TO anon;
GRANT ALL ON TABLE public.social_posts TO authenticated;
GRANT ALL ON TABLE public.social_posts TO service_role;
GRANT SELECT,INSERT ON TABLE public.social_posts TO sandbox_exec;


--
-- Name: SEQUENCE social_posts_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.social_posts_id_seq TO anon;
GRANT ALL ON SEQUENCE public.social_posts_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.social_posts_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.social_posts_id_seq TO sandbox_exec;


--
-- Name: TABLE source_breaker; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.source_breaker TO anon;
GRANT ALL ON TABLE public.source_breaker TO authenticated;
GRANT ALL ON TABLE public.source_breaker TO service_role;
GRANT SELECT,INSERT ON TABLE public.source_breaker TO sandbox_exec;


--
-- Name: TABLE source_config; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.source_config TO anon;
GRANT ALL ON TABLE public.source_config TO authenticated;
GRANT ALL ON TABLE public.source_config TO service_role;
GRANT SELECT,INSERT ON TABLE public.source_config TO sandbox_exec;


--
-- Name: TABLE source_perf_daily; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.source_perf_daily TO anon;
GRANT ALL ON TABLE public.source_perf_daily TO authenticated;
GRANT ALL ON TABLE public.source_perf_daily TO service_role;
GRANT SELECT,INSERT ON TABLE public.source_perf_daily TO sandbox_exec;


--
-- Name: TABLE source_registry; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.source_registry TO anon;
GRANT ALL ON TABLE public.source_registry TO authenticated;
GRANT ALL ON TABLE public.source_registry TO service_role;
GRANT SELECT,INSERT ON TABLE public.source_registry TO sandbox_exec;


--
-- Name: TABLE source_run_history; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.source_run_history TO anon;
GRANT ALL ON TABLE public.source_run_history TO authenticated;
GRANT ALL ON TABLE public.source_run_history TO service_role;
GRANT SELECT,INSERT ON TABLE public.source_run_history TO sandbox_exec;


--
-- Name: SEQUENCE source_run_history_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.source_run_history_id_seq TO anon;
GRANT ALL ON SEQUENCE public.source_run_history_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.source_run_history_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.source_run_history_id_seq TO sandbox_exec;


--
-- Name: TABLE source_runs; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.source_runs TO anon;
GRANT ALL ON TABLE public.source_runs TO authenticated;
GRANT ALL ON TABLE public.source_runs TO service_role;
GRANT SELECT,INSERT ON TABLE public.source_runs TO sandbox_exec;


--
-- Name: TABLE station_locations; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.station_locations TO anon;
GRANT ALL ON TABLE public.station_locations TO authenticated;
GRANT ALL ON TABLE public.station_locations TO service_role;
GRANT SELECT,INSERT ON TABLE public.station_locations TO sandbox_exec;


--
-- Name: TABLE station_snapshots; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.station_snapshots TO anon;
GRANT ALL ON TABLE public.station_snapshots TO authenticated;
GRANT ALL ON TABLE public.station_snapshots TO service_role;
GRANT SELECT,INSERT ON TABLE public.station_snapshots TO sandbox_exec;


--
-- Name: SEQUENCE station_snapshots_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.station_snapshots_id_seq TO anon;
GRANT ALL ON SEQUENCE public.station_snapshots_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.station_snapshots_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.station_snapshots_id_seq TO sandbox_exec;


--
-- Name: TABLE tax_deadlines; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.tax_deadlines TO anon;
GRANT ALL ON TABLE public.tax_deadlines TO authenticated;
GRANT ALL ON TABLE public.tax_deadlines TO service_role;
GRANT SELECT,INSERT ON TABLE public.tax_deadlines TO sandbox_exec;


--
-- Name: SEQUENCE tax_deadlines_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.tax_deadlines_id_seq TO anon;
GRANT ALL ON SEQUENCE public.tax_deadlines_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.tax_deadlines_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.tax_deadlines_id_seq TO sandbox_exec;


--
-- Name: TABLE user_roles; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.user_roles TO anon;
GRANT ALL ON TABLE public.user_roles TO authenticated;
GRANT ALL ON TABLE public.user_roles TO service_role;
GRANT SELECT,INSERT ON TABLE public.user_roles TO sandbox_exec;


--
-- Name: TABLE weather_station_obs; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.weather_station_obs TO anon;
GRANT ALL ON TABLE public.weather_station_obs TO authenticated;
GRANT ALL ON TABLE public.weather_station_obs TO service_role;
GRANT SELECT,INSERT ON TABLE public.weather_station_obs TO sandbox_exec;


--
-- Name: SEQUENCE weather_station_obs_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON SEQUENCE public.weather_station_obs_id_seq TO anon;
GRANT ALL ON SEQUENCE public.weather_station_obs_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.weather_station_obs_id_seq TO service_role;
GRANT SELECT,USAGE ON SEQUENCE public.weather_station_obs_id_seq TO sandbox_exec;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,USAGE ON SEQUENCES TO sandbox_exec;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT ON TABLES TO sandbox_exec;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--



-- Private storage buckets (raw evidence files and AI brief images). Only the service role reads/writes them.
INSERT INTO storage.buckets (id, name, public) VALUES ('evidence','evidence',false), ('brief-images','brief-images',false)
ON CONFLICT (id) DO NOTHING;
