#!/usr/bin/env bash
# Maintainers: regenerate database/schema.sql and database/seed.sql from a live database
# after adding a migration. Needs pg_dump/psql 17+.  Usage: DATABASE_URL=... ./scripts/export-db.sh
set -euo pipefail
cd "$(dirname "$0")/.."
: "${DATABASE_URL:?Set DATABASE_URL}"
strip() { sed -e '/^\\restrict/d' -e '/^\\unrestrict/d' "$@"; }

{
  cat <<'H'
-- Thailand Daily Signals — database structure (public schema)
-- Generated by scripts/export-db.sh from the live database. Do not edit by hand; add a migration instead.
-- Prerequisites: Supabase (cloud or self-hosted) — provides roles anon/authenticated/service_role,
-- the auth schema, storage and the pg_cron + pg_net extensions. For plain Postgres see database/README.md.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;
H
  pg_dump "$DATABASE_URL" --schema-only --no-owner --schema=public | strip \
    | sed -e 's/^CREATE SCHEMA public;/CREATE SCHEMA IF NOT EXISTS public;/' -e '/^COMMENT ON SCHEMA public/d'
  cat <<'H'

-- Private storage buckets (raw evidence files and AI brief images). Only the service role reads/writes them.
INSERT INTO storage.buckets (id, name, public) VALUES ('evidence','evidence',false), ('brief-images','brief-images',false)
ON CONFLICT (id) DO NOTHING;
H
} > database/schema.sql

TABLES=(families metrics source_registry source_config holidays tax_deadlines release_calendar)
{
  echo "-- Setup data: categories, metrics + official thresholds, source registry/settings, calendars."
  echo "-- No collected readings, users, roles, evidence or logs. Safe to re-run (ON CONFLICT DO NOTHING)."
  echo "SET session_replication_role = replica;"
  pg_dump "$DATABASE_URL" --data-only --no-owner --inserts --on-conflict-do-nothing $(printf -- '-t public.%s ' "${TABLES[@]}") \
    | strip | sed '/^SELECT pg_catalog.setval/d'
  echo "INSERT INTO public.app_settings (key, value, updated_at) SELECT key, value, now() FROM (VALUES"
  psql "$DATABASE_URL" -Atc "select string_agg(format('(%L, %L)', key, value), E',\n') from app_settings where key in ('holiday_url','longdo_mode','thaiwater_mode')"
  echo ") v(key, value) ON CONFLICT (key) DO NOTHING;"
  echo "SET session_replication_role = DEFAULT;"
} > database/seed.sql
echo "✓ database/schema.sql and database/seed.sql regenerated"
