/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataRouteImport } from './routes/data'
import { Route as FailuresRouteImport } from './routes/failures'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as AgenciesIndexRouteImport } from './routes/agencies.index'
import { Route as AgenciesAgencyRouteImport } from './routes/agencies.$agency'
import { Route as BriefIndexRouteImport } from './routes/brief.index'
import { Route as BriefDateRouteImport } from './routes/brief.$date'
import { Route as DayDateRouteImport } from './routes/day.$date'
import { Route as SignalsFamilyRouteImport } from './routes/signals.$family'
import { Route as ApiPublicBriefRouteImport } from './routes/api/public/brief'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const FailuresRoute = FailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/agencies/',
  path: '/agencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesAgencyRoute = AgenciesAgencyRouteImport.update({
  id: '/agencies/$agency',
  path: '/agencies/$agency',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefIndexRoute = BriefIndexRouteImport.update({
  id: '/brief/',
  path: '/brief/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefDateRoute = BriefDateRouteImport.update({
  id: '/brief/$date',
  path: '/brief/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDateRoute = DayDateRouteImport.update({
  id: '/day/$date',
  path: '/day/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsFamilyRoute = SignalsFamilyRouteImport.update({
  id: '/signals/$family',
  path: '/signals/$family',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBriefRoute = ApiPublicBriefRouteImport.update({
  id: '/api/public/brief',
  path: '/api/public/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/failures': typeof FailuresRoute
  '/monitor': typeof MonitorRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/agencies/$agency': typeof AgenciesAgencyRoute
  '/brief/$date': typeof BriefDateRoute
  '/day/$date': typeof DayDateRoute
  '/signals/$family': typeof SignalsFamilyRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/brief/': typeof BriefIndexRoute
  '/api/public/brief': typeof ApiPublicBriefRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/failures': typeof FailuresRoute
  '/monitor': typeof MonitorRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/agencies/$agency': typeof AgenciesAgencyRoute
  '/brief/$date': typeof BriefDateRoute
  '/day/$date': typeof DayDateRoute
  '/signals/$family': typeof SignalsFamilyRoute
  '/agencies': typeof AgenciesIndexRoute
  '/brief': typeof BriefIndexRoute
  '/api/public/brief': typeof ApiPublicBriefRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/failures': typeof FailuresRoute
  '/monitor': typeof MonitorRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/agencies/$agency': typeof AgenciesAgencyRoute
  '/brief/$date': typeof BriefDateRoute
  '/day/$date': typeof DayDateRoute
  '/signals/$family': typeof SignalsFamilyRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/brief/': typeof BriefIndexRoute
  '/api/public/brief': typeof ApiPublicBriefRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/failures'
    | '/monitor'
    | '/settings'
    | '/sources'
    | '/agencies/$agency'
    | '/brief/$date'
    | '/day/$date'
    | '/signals/$family'
    | '/agencies/'
    | '/brief/'
    | '/api/public/brief'
    | '/api/public/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data'
    | '/failures'
    | '/monitor'
    | '/settings'
    | '/sources'
    | '/agencies/$agency'
    | '/brief/$date'
    | '/day/$date'
    | '/signals/$family'
    | '/agencies'
    | '/brief'
    | '/api/public/brief'
    | '/api/public/ingest'
  id:
    | '__root__'
    | '/'
    | '/data'
    | '/failures'
    | '/monitor'
    | '/settings'
    | '/sources'
    | '/agencies/$agency'
    | '/brief/$date'
    | '/day/$date'
    | '/signals/$family'
    | '/agencies/'
    | '/brief/'
    | '/api/public/brief'
    | '/api/public/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  FailuresRoute: typeof FailuresRoute
  MonitorRoute: typeof MonitorRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  AgenciesAgencyRoute: typeof AgenciesAgencyRoute
  BriefDateRoute: typeof BriefDateRoute
  DayDateRoute: typeof DayDateRoute
  SignalsFamilyRoute: typeof SignalsFamilyRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
  BriefIndexRoute: typeof BriefIndexRoute
  ApiPublicBriefRoute: typeof ApiPublicBriefRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failures': {
      id: '/failures'
      path: '/failures'
      fullPath: '/failures'
      preLoaderRoute: typeof FailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/agencies'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/$agency': {
      id: '/agencies/$agency'
      path: '/agencies/$agency'
      fullPath: '/agencies/$agency'
      preLoaderRoute: typeof AgenciesAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/': {
      id: '/brief/'
      path: '/brief'
      fullPath: '/brief/'
      preLoaderRoute: typeof BriefIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$date': {
      id: '/brief/$date'
      path: '/brief/$date'
      fullPath: '/brief/$date'
      preLoaderRoute: typeof BriefDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$date': {
      id: '/day/$date'
      path: '/day/$date'
      fullPath: '/day/$date'
      preLoaderRoute: typeof DayDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/$family': {
      id: '/signals/$family'
      path: '/signals/$family'
      fullPath: '/signals/$family'
      preLoaderRoute: typeof SignalsFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brief': {
      id: '/api/public/brief'
      path: '/api/public/brief'
      fullPath: '/api/public/brief'
      preLoaderRoute: typeof ApiPublicBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  FailuresRoute: FailuresRoute,
  MonitorRoute: MonitorRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  AgenciesAgencyRoute: AgenciesAgencyRoute,
  BriefDateRoute: BriefDateRoute,
  DayDateRoute: DayDateRoute,
  SignalsFamilyRoute: SignalsFamilyRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
  BriefIndexRoute: BriefIndexRoute,
  ApiPublicBriefRoute: ApiPublicBriefRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
