/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as DataAllRouteImport } from './routes/data-all'
import { Route as DataMapRouteImport } from './routes/data-map'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as FailuresRouteImport } from './routes/failures'
import { Route as KeyDataRouteImport } from './routes/key-data'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AdminCalendarRouteImport } from './routes/_admin/calendar'
import { Route as AdminDataRouteImport } from './routes/_admin/data'
import { Route as AdminEvidenceRouteImport } from './routes/_admin/evidence'
import { Route as AdminImpactRouteImport } from './routes/_admin/impact'
import { Route as AdminMethodRouteImport } from './routes/_admin/method'
import { Route as AdminRawLogRouteImport } from './routes/_admin/raw-log'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminSourcesRouteImport } from './routes/_admin/sources'
import { Route as AdminTrackingRouteImport } from './routes/_admin/tracking'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as BriefIndexRouteImport } from './routes/brief.index'
import { Route as BriefDateRouteImport } from './routes/brief.$date'
import { Route as DayDateRouteImport } from './routes/day.$date'
import { Route as DevelopersIndexRouteImport } from './routes/developers.index'
import { Route as DevelopersApiRouteImport } from './routes/developers.api'
import { Route as DevelopersMcpRouteImport } from './routes/developers.mcp'
import { Route as SignalsFamilyRouteImport } from './routes/signals.$family'
import { Route as AdminAgenciesIndexRouteImport } from './routes/_admin/agencies.index'
import { Route as AdminAgenciesAgencyRouteImport } from './routes/_admin/agencies.$agency'
import { Route as AdminEventsIndexRouteImport } from './routes/_admin/events.index'
import { Route as AdminEventsIdRouteImport } from './routes/_admin/events.$id'
import { Route as ApiPublicBriefRouteImport } from './routes/api/public/brief'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicOpenapiDotjsonRouteImport } from './routes/api/public/openapi[.]json'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1/$'
import { Route as ApiPublicOgBriefDateRouteImport } from './routes/api/public/og/brief.$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DataAllRoute = DataAllRouteImport.update({
  id: '/data-all',
  path: '/data-all',
  getParentRoute: () => rootRouteImport,
} as any)
const DataMapRoute = DataMapRouteImport.update({
  id: '/data-map',
  path: '/data-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const FailuresRoute = FailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyDataRoute = KeyDataRouteImport.update({
  id: '/key-data',
  path: '/key-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEvidenceRoute = AdminEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImpactRoute = AdminImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMethodRoute = AdminMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRawLogRoute = AdminRawLogRouteImport.update({
  id: '/raw-log',
  path: '/raw-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTrackingRoute = AdminTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefIndexRoute = BriefIndexRouteImport.update({
  id: '/brief/',
  path: '/brief/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefDateRoute = BriefDateRouteImport.update({
  id: '/brief/$date',
  path: '/brief/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDateRoute = DayDateRouteImport.update({
  id: '/day/$date',
  path: '/day/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersIndexRoute = DevelopersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevelopersRoute,
} as any)
const DevelopersApiRoute = DevelopersApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DevelopersRoute,
} as any)
const DevelopersMcpRoute = DevelopersMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => DevelopersRoute,
} as any)
const SignalsFamilyRoute = SignalsFamilyRouteImport.update({
  id: '/signals/$family',
  path: '/signals/$family',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgenciesIndexRoute = AdminAgenciesIndexRouteImport.update({
  id: '/agencies/',
  path: '/agencies/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAgenciesAgencyRoute = AdminAgenciesAgencyRouteImport.update({
  id: '/agencies/$agency',
  path: '/agencies/$agency',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicBriefRoute = ApiPublicBriefRouteImport.update({
  id: '/api/public/brief',
  path: '/api/public/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenapiDotjsonRoute = ApiPublicOpenapiDotjsonRouteImport.update({
  id: '/api/public/openapi.json',
  path: '/api/public/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgBriefDateRoute = ApiPublicOgBriefDateRouteImport.update({
  id: '/api/public/og/brief/$date',
  path: '/api/public/og/brief/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-all': typeof DataAllRoute
  '/data-map': typeof DataMapRoute
  '/developers': typeof DevelopersRouteWithChildren
  '/failures': typeof FailuresRoute
  '/key-data': typeof KeyDataRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminAdminRoute
  '/calendar': typeof AdminCalendarRoute
  '/data': typeof AdminDataRoute
  '/evidence': typeof AdminEvidenceRoute
  '/impact': typeof AdminImpactRoute
  '/method': typeof AdminMethodRoute
  '/raw-log': typeof AdminRawLogRoute
  '/settings': typeof AdminSettingsRoute
  '/sources': typeof AdminSourcesRoute
  '/tracking': typeof AdminTrackingRoute
  '/admin/login': typeof AdminLoginRoute
  '/brief/$date': typeof BriefDateRoute
  '/day/$date': typeof DayDateRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/mcp': typeof DevelopersMcpRoute
  '/signals/$family': typeof SignalsFamilyRoute
  '/brief/': typeof BriefIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/agencies/$agency': typeof AdminAgenciesAgencyRoute
  '/events/$id': typeof AdminEventsIdRoute
  '/api/public/brief': typeof ApiPublicBriefRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/agencies/': typeof AdminAgenciesIndexRoute
  '/events/': typeof AdminEventsIndexRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/api/public/og/brief/$date': typeof ApiPublicOgBriefDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-all': typeof DataAllRoute
  '/data-map': typeof DataMapRoute
  '/failures': typeof FailuresRoute
  '/key-data': typeof KeyDataRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminAdminRoute
  '/calendar': typeof AdminCalendarRoute
  '/data': typeof AdminDataRoute
  '/evidence': typeof AdminEvidenceRoute
  '/impact': typeof AdminImpactRoute
  '/method': typeof AdminMethodRoute
  '/raw-log': typeof AdminRawLogRoute
  '/settings': typeof AdminSettingsRoute
  '/sources': typeof AdminSourcesRoute
  '/tracking': typeof AdminTrackingRoute
  '/admin/login': typeof AdminLoginRoute
  '/brief/$date': typeof BriefDateRoute
  '/day/$date': typeof DayDateRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/mcp': typeof DevelopersMcpRoute
  '/signals/$family': typeof SignalsFamilyRoute
  '/brief': typeof BriefIndexRoute
  '/developers': typeof DevelopersIndexRoute
  '/agencies/$agency': typeof AdminAgenciesAgencyRoute
  '/events/$id': typeof AdminEventsIdRoute
  '/api/public/brief': typeof ApiPublicBriefRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/agencies': typeof AdminAgenciesIndexRoute
  '/events': typeof AdminEventsIndexRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/api/public/og/brief/$date': typeof ApiPublicOgBriefDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/data-all': typeof DataAllRoute
  '/data-map': typeof DataMapRoute
  '/developers': typeof DevelopersRouteWithChildren
  '/failures': typeof FailuresRoute
  '/key-data': typeof KeyDataRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_admin/admin': typeof AdminAdminRoute
  '/_admin/calendar': typeof AdminCalendarRoute
  '/_admin/data': typeof AdminDataRoute
  '/_admin/evidence': typeof AdminEvidenceRoute
  '/_admin/impact': typeof AdminImpactRoute
  '/_admin/method': typeof AdminMethodRoute
  '/_admin/raw-log': typeof AdminRawLogRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/sources': typeof AdminSourcesRoute
  '/_admin/tracking': typeof AdminTrackingRoute
  '/admin/login': typeof AdminLoginRoute
  '/brief/$date': typeof BriefDateRoute
  '/day/$date': typeof DayDateRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/mcp': typeof DevelopersMcpRoute
  '/signals/$family': typeof SignalsFamilyRoute
  '/brief/': typeof BriefIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/_admin/agencies/$agency': typeof AdminAgenciesAgencyRoute
  '/_admin/events/$id': typeof AdminEventsIdRoute
  '/api/public/brief': typeof ApiPublicBriefRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/_admin/agencies/': typeof AdminAgenciesIndexRoute
  '/_admin/events/': typeof AdminEventsIndexRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/api/public/og/brief/$date': typeof ApiPublicOgBriefDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-all'
    | '/data-map'
    | '/developers'
    | '/failures'
    | '/key-data'
    | '/llms.txt'
    | '/mcp'
    | '/search'
    | '/sitemap'
    | '/sitemap.xml'
    | '/admin'
    | '/calendar'
    | '/data'
    | '/evidence'
    | '/impact'
    | '/method'
    | '/raw-log'
    | '/settings'
    | '/sources'
    | '/tracking'
    | '/admin/login'
    | '/brief/$date'
    | '/day/$date'
    | '/developers/api'
    | '/developers/mcp'
    | '/signals/$family'
    | '/brief/'
    | '/developers/'
    | '/agencies/$agency'
    | '/events/$id'
    | '/api/public/brief'
    | '/api/public/ingest'
    | '/api/public/openapi.json'
    | '/agencies/'
    | '/events/'
    | '/api/public/v1/$'
    | '/api/public/og/brief/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-all'
    | '/data-map'
    | '/failures'
    | '/key-data'
    | '/llms.txt'
    | '/mcp'
    | '/search'
    | '/sitemap'
    | '/sitemap.xml'
    | '/admin'
    | '/calendar'
    | '/data'
    | '/evidence'
    | '/impact'
    | '/method'
    | '/raw-log'
    | '/settings'
    | '/sources'
    | '/tracking'
    | '/admin/login'
    | '/brief/$date'
    | '/day/$date'
    | '/developers/api'
    | '/developers/mcp'
    | '/signals/$family'
    | '/brief'
    | '/developers'
    | '/agencies/$agency'
    | '/events/$id'
    | '/api/public/brief'
    | '/api/public/ingest'
    | '/api/public/openapi.json'
    | '/agencies'
    | '/events'
    | '/api/public/v1/$'
    | '/api/public/og/brief/$date'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/data-all'
    | '/data-map'
    | '/developers'
    | '/failures'
    | '/key-data'
    | '/llms.txt'
    | '/mcp'
    | '/search'
    | '/sitemap'
    | '/sitemap.xml'
    | '/_admin/admin'
    | '/_admin/calendar'
    | '/_admin/data'
    | '/_admin/evidence'
    | '/_admin/impact'
    | '/_admin/method'
    | '/_admin/raw-log'
    | '/_admin/settings'
    | '/_admin/sources'
    | '/_admin/tracking'
    | '/admin/login'
    | '/brief/$date'
    | '/day/$date'
    | '/developers/api'
    | '/developers/mcp'
    | '/signals/$family'
    | '/brief/'
    | '/developers/'
    | '/_admin/agencies/$agency'
    | '/_admin/events/$id'
    | '/api/public/brief'
    | '/api/public/ingest'
    | '/api/public/openapi.json'
    | '/_admin/agencies/'
    | '/_admin/events/'
    | '/api/public/v1/$'
    | '/api/public/og/brief/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DataAllRoute: typeof DataAllRoute
  DataMapRoute: typeof DataMapRoute
  DevelopersRoute: typeof DevelopersRouteWithChildren
  FailuresRoute: typeof FailuresRoute
  KeyDataRoute: typeof KeyDataRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  SearchRoute: typeof SearchRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BriefDateRoute: typeof BriefDateRoute
  DayDateRoute: typeof DayDateRoute
  SignalsFamilyRoute: typeof SignalsFamilyRoute
  BriefIndexRoute: typeof BriefIndexRoute
  ApiPublicBriefRoute: typeof ApiPublicBriefRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicOpenapiDotjsonRoute: typeof ApiPublicOpenapiDotjsonRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
  ApiPublicOgBriefDateRoute: typeof ApiPublicOgBriefDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-all': {
      id: '/data-all'
      path: '/data-all'
      fullPath: '/data-all'
      preLoaderRoute: typeof DataAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-map': {
      id: '/data-map'
      path: '/data-map'
      fullPath: '/data-map'
      preLoaderRoute: typeof DataMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failures': {
      id: '/failures'
      path: '/failures'
      fullPath: '/failures'
      preLoaderRoute: typeof FailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key-data': {
      id: '/key-data'
      path: '/key-data'
      fullPath: '/key-data'
      preLoaderRoute: typeof KeyDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/calendar': {
      id: '/_admin/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/data': {
      id: '/_admin/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/evidence': {
      id: '/_admin/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof AdminEvidenceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/impact': {
      id: '/_admin/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof AdminImpactRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/method': {
      id: '/_admin/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof AdminMethodRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/raw-log': {
      id: '/_admin/raw-log'
      path: '/raw-log'
      fullPath: '/raw-log'
      preLoaderRoute: typeof AdminRawLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/sources': {
      id: '/_admin/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/tracking': {
      id: '/_admin/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AdminTrackingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/': {
      id: '/brief/'
      path: '/brief'
      fullPath: '/brief/'
      preLoaderRoute: typeof BriefIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$date': {
      id: '/brief/$date'
      path: '/brief/$date'
      fullPath: '/brief/$date'
      preLoaderRoute: typeof BriefDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$date': {
      id: '/day/$date'
      path: '/day/$date'
      fullPath: '/day/$date'
      preLoaderRoute: typeof DayDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/': {
      id: '/developers/'
      path: '/'
      fullPath: '/developers/'
      preLoaderRoute: typeof DevelopersIndexRouteImport
      parentRoute: typeof DevelopersRoute
    }
    '/developers/api': {
      id: '/developers/api'
      path: '/api'
      fullPath: '/developers/api'
      preLoaderRoute: typeof DevelopersApiRouteImport
      parentRoute: typeof DevelopersRoute
    }
    '/developers/mcp': {
      id: '/developers/mcp'
      path: '/mcp'
      fullPath: '/developers/mcp'
      preLoaderRoute: typeof DevelopersMcpRouteImport
      parentRoute: typeof DevelopersRoute
    }
    '/signals/$family': {
      id: '/signals/$family'
      path: '/signals/$family'
      fullPath: '/signals/$family'
      preLoaderRoute: typeof SignalsFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/agencies/': {
      id: '/_admin/agencies/'
      path: '/agencies'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AdminAgenciesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/agencies/$agency': {
      id: '/_admin/agencies/$agency'
      path: '/agencies/$agency'
      fullPath: '/agencies/$agency'
      preLoaderRoute: typeof AdminAgenciesAgencyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/events/': {
      id: '/_admin/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/events/$id': {
      id: '/_admin/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/brief': {
      id: '/api/public/brief'
      path: '/api/public/brief'
      fullPath: '/api/public/brief'
      preLoaderRoute: typeof ApiPublicBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openapi.json': {
      id: '/api/public/openapi.json'
      path: '/api/public/openapi.json'
      fullPath: '/api/public/openapi.json'
      preLoaderRoute: typeof ApiPublicOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/brief/$date': {
      id: '/api/public/og/brief/$date'
      path: '/api/public/og/brief/$date'
      fullPath: '/api/public/og/brief/$date'
      preLoaderRoute: typeof ApiPublicOgBriefDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminEvidenceRoute: typeof AdminEvidenceRoute
  AdminImpactRoute: typeof AdminImpactRoute
  AdminMethodRoute: typeof AdminMethodRoute
  AdminRawLogRoute: typeof AdminRawLogRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminTrackingRoute: typeof AdminTrackingRoute
  AdminAgenciesAgencyRoute: typeof AdminAgenciesAgencyRoute
  AdminEventsIdRoute: typeof AdminEventsIdRoute
  AdminAgenciesIndexRoute: typeof AdminAgenciesIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminDataRoute: AdminDataRoute,
  AdminEvidenceRoute: AdminEvidenceRoute,
  AdminImpactRoute: AdminImpactRoute,
  AdminMethodRoute: AdminMethodRoute,
  AdminRawLogRoute: AdminRawLogRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminTrackingRoute: AdminTrackingRoute,
  AdminAgenciesAgencyRoute: AdminAgenciesAgencyRoute,
  AdminEventsIdRoute: AdminEventsIdRoute,
  AdminAgenciesIndexRoute: AdminAgenciesIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DevelopersRouteChildren {
  DevelopersApiRoute: typeof DevelopersApiRoute
  DevelopersMcpRoute: typeof DevelopersMcpRoute
  DevelopersIndexRoute: typeof DevelopersIndexRoute
}

const DevelopersRouteChildren: DevelopersRouteChildren = {
  DevelopersApiRoute: DevelopersApiRoute,
  DevelopersMcpRoute: DevelopersMcpRoute,
  DevelopersIndexRoute: DevelopersIndexRoute,
}

const DevelopersRouteWithChildren = DevelopersRoute._addFileChildren(
  DevelopersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DataAllRoute: DataAllRoute,
  DataMapRoute: DataMapRoute,
  DevelopersRoute: DevelopersRouteWithChildren,
  FailuresRoute: FailuresRoute,
  KeyDataRoute: KeyDataRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  SearchRoute: SearchRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  BriefDateRoute: BriefDateRoute,
  DayDateRoute: DayDateRoute,
  SignalsFamilyRoute: SignalsFamilyRoute,
  BriefIndexRoute: BriefIndexRoute,
  ApiPublicBriefRoute: ApiPublicBriefRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicOpenapiDotjsonRoute: ApiPublicOpenapiDotjsonRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
  ApiPublicOgBriefDateRoute: ApiPublicOgBriefDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
