/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DataRouteImport } from './routes/data'
import { Route as DataAllRouteImport } from './routes/data-all'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as FailuresRouteImport } from './routes/failures'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as KeyDataRouteImport } from './routes/key-data'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MethodRouteImport } from './routes/method'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as AgenciesIndexRouteImport } from './routes/agencies.index'
import { Route as AgenciesAgencyRouteImport } from './routes/agencies.$agency'
import { Route as BriefIndexRouteImport } from './routes/brief.index'
import { Route as BriefDateRouteImport } from './routes/brief.$date'
import { Route as DayDateRouteImport } from './routes/day.$date'
import { Route as DevelopersIndexRouteImport } from './routes/developers.index'
import { Route as DevelopersApiRouteImport } from './routes/developers.api'
import { Route as DevelopersMcpRouteImport } from './routes/developers.mcp'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as SignalsFamilyRouteImport } from './routes/signals.$family'
import { Route as ApiPublicBriefRouteImport } from './routes/api/public/brief'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicOpenapiDotjsonRouteImport } from './routes/api/public/openapi[.]json'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DataAllRoute = DataAllRouteImport.update({
  id: '/data-all',
  path: '/data-all',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FailuresRoute = FailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyDataRoute = KeyDataRouteImport.update({
  id: '/key-data',
  path: '/key-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/agencies/',
  path: '/agencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesAgencyRoute = AgenciesAgencyRouteImport.update({
  id: '/agencies/$agency',
  path: '/agencies/$agency',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefIndexRoute = BriefIndexRouteImport.update({
  id: '/brief/',
  path: '/brief/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefDateRoute = BriefDateRouteImport.update({
  id: '/brief/$date',
  path: '/brief/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDateRoute = DayDateRouteImport.update({
  id: '/day/$date',
  path: '/day/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersIndexRoute = DevelopersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevelopersRoute,
} as any)
const DevelopersApiRoute = DevelopersApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DevelopersRoute,
} as any)
const DevelopersMcpRoute = DevelopersMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => DevelopersRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsFamilyRoute = SignalsFamilyRouteImport.update({
  id: '/signals/$family',
  path: '/signals/$family',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBriefRoute = ApiPublicBriefRouteImport.update({
  id: '/api/public/brief',
  path: '/api/public/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenapiDotjsonRoute = ApiPublicOpenapiDotjsonRouteImport.update({
  id: '/api/public/openapi.json',
  path: '/api/public/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/data': typeof DataRoute
  '/data-all': typeof DataAllRoute
  '/developers': typeof DevelopersRouteWithChildren
  '/evidence': typeof EvidenceRoute
  '/failures': typeof FailuresRoute
  '/impact': typeof ImpactRoute
  '/key-data': typeof KeyDataRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/method': typeof MethodRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/tracking': typeof TrackingRoute
  '/agencies/$agency': typeof AgenciesAgencyRoute
  '/brief/$date': typeof BriefDateRoute
  '/day/$date': typeof DayDateRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/mcp': typeof DevelopersMcpRoute
  '/events/$id': typeof EventsIdRoute
  '/signals/$family': typeof SignalsFamilyRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/brief/': typeof BriefIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/api/public/brief': typeof ApiPublicBriefRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/data': typeof DataRoute
  '/data-all': typeof DataAllRoute
  '/evidence': typeof EvidenceRoute
  '/failures': typeof FailuresRoute
  '/impact': typeof ImpactRoute
  '/key-data': typeof KeyDataRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/method': typeof MethodRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/tracking': typeof TrackingRoute
  '/agencies/$agency': typeof AgenciesAgencyRoute
  '/brief/$date': typeof BriefDateRoute
  '/day/$date': typeof DayDateRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/mcp': typeof DevelopersMcpRoute
  '/events/$id': typeof EventsIdRoute
  '/signals/$family': typeof SignalsFamilyRoute
  '/agencies': typeof AgenciesIndexRoute
  '/brief': typeof BriefIndexRoute
  '/developers': typeof DevelopersIndexRoute
  '/events': typeof EventsIndexRoute
  '/api/public/brief': typeof ApiPublicBriefRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/data': typeof DataRoute
  '/data-all': typeof DataAllRoute
  '/developers': typeof DevelopersRouteWithChildren
  '/evidence': typeof EvidenceRoute
  '/failures': typeof FailuresRoute
  '/impact': typeof ImpactRoute
  '/key-data': typeof KeyDataRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/method': typeof MethodRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/tracking': typeof TrackingRoute
  '/agencies/$agency': typeof AgenciesAgencyRoute
  '/brief/$date': typeof BriefDateRoute
  '/day/$date': typeof DayDateRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/mcp': typeof DevelopersMcpRoute
  '/events/$id': typeof EventsIdRoute
  '/signals/$family': typeof SignalsFamilyRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/brief/': typeof BriefIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/api/public/brief': typeof ApiPublicBriefRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/data'
    | '/data-all'
    | '/developers'
    | '/evidence'
    | '/failures'
    | '/impact'
    | '/key-data'
    | '/llms.txt'
    | '/mcp'
    | '/method'
    | '/settings'
    | '/sitemap'
    | '/sitemap.xml'
    | '/sources'
    | '/tracking'
    | '/agencies/$agency'
    | '/brief/$date'
    | '/day/$date'
    | '/developers/api'
    | '/developers/mcp'
    | '/events/$id'
    | '/signals/$family'
    | '/agencies/'
    | '/brief/'
    | '/developers/'
    | '/events/'
    | '/api/public/brief'
    | '/api/public/ingest'
    | '/api/public/openapi.json'
    | '/api/public/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/data'
    | '/data-all'
    | '/evidence'
    | '/failures'
    | '/impact'
    | '/key-data'
    | '/llms.txt'
    | '/mcp'
    | '/method'
    | '/settings'
    | '/sitemap'
    | '/sitemap.xml'
    | '/sources'
    | '/tracking'
    | '/agencies/$agency'
    | '/brief/$date'
    | '/day/$date'
    | '/developers/api'
    | '/developers/mcp'
    | '/events/$id'
    | '/signals/$family'
    | '/agencies'
    | '/brief'
    | '/developers'
    | '/events'
    | '/api/public/brief'
    | '/api/public/ingest'
    | '/api/public/openapi.json'
    | '/api/public/v1/$'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/data'
    | '/data-all'
    | '/developers'
    | '/evidence'
    | '/failures'
    | '/impact'
    | '/key-data'
    | '/llms.txt'
    | '/mcp'
    | '/method'
    | '/settings'
    | '/sitemap'
    | '/sitemap.xml'
    | '/sources'
    | '/tracking'
    | '/agencies/$agency'
    | '/brief/$date'
    | '/day/$date'
    | '/developers/api'
    | '/developers/mcp'
    | '/events/$id'
    | '/signals/$family'
    | '/agencies/'
    | '/brief/'
    | '/developers/'
    | '/events/'
    | '/api/public/brief'
    | '/api/public/ingest'
    | '/api/public/openapi.json'
    | '/api/public/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DataRoute: typeof DataRoute
  DataAllRoute: typeof DataAllRoute
  DevelopersRoute: typeof DevelopersRouteWithChildren
  EvidenceRoute: typeof EvidenceRoute
  FailuresRoute: typeof FailuresRoute
  ImpactRoute: typeof ImpactRoute
  KeyDataRoute: typeof KeyDataRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  MethodRoute: typeof MethodRoute
  SettingsRoute: typeof SettingsRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcesRoute: typeof SourcesRoute
  TrackingRoute: typeof TrackingRoute
  AgenciesAgencyRoute: typeof AgenciesAgencyRoute
  BriefDateRoute: typeof BriefDateRoute
  DayDateRoute: typeof DayDateRoute
  EventsIdRoute: typeof EventsIdRoute
  SignalsFamilyRoute: typeof SignalsFamilyRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
  BriefIndexRoute: typeof BriefIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiPublicBriefRoute: typeof ApiPublicBriefRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicOpenapiDotjsonRoute: typeof ApiPublicOpenapiDotjsonRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-all': {
      id: '/data-all'
      path: '/data-all'
      fullPath: '/data-all'
      preLoaderRoute: typeof DataAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failures': {
      id: '/failures'
      path: '/failures'
      fullPath: '/failures'
      preLoaderRoute: typeof FailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key-data': {
      id: '/key-data'
      path: '/key-data'
      fullPath: '/key-data'
      preLoaderRoute: typeof KeyDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/agencies'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/$agency': {
      id: '/agencies/$agency'
      path: '/agencies/$agency'
      fullPath: '/agencies/$agency'
      preLoaderRoute: typeof AgenciesAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/': {
      id: '/brief/'
      path: '/brief'
      fullPath: '/brief/'
      preLoaderRoute: typeof BriefIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$date': {
      id: '/brief/$date'
      path: '/brief/$date'
      fullPath: '/brief/$date'
      preLoaderRoute: typeof BriefDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$date': {
      id: '/day/$date'
      path: '/day/$date'
      fullPath: '/day/$date'
      preLoaderRoute: typeof DayDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/': {
      id: '/developers/'
      path: '/'
      fullPath: '/developers/'
      preLoaderRoute: typeof DevelopersIndexRouteImport
      parentRoute: typeof DevelopersRoute
    }
    '/developers/api': {
      id: '/developers/api'
      path: '/api'
      fullPath: '/developers/api'
      preLoaderRoute: typeof DevelopersApiRouteImport
      parentRoute: typeof DevelopersRoute
    }
    '/developers/mcp': {
      id: '/developers/mcp'
      path: '/mcp'
      fullPath: '/developers/mcp'
      preLoaderRoute: typeof DevelopersMcpRouteImport
      parentRoute: typeof DevelopersRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/$family': {
      id: '/signals/$family'
      path: '/signals/$family'
      fullPath: '/signals/$family'
      preLoaderRoute: typeof SignalsFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brief': {
      id: '/api/public/brief'
      path: '/api/public/brief'
      fullPath: '/api/public/brief'
      preLoaderRoute: typeof ApiPublicBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openapi.json': {
      id: '/api/public/openapi.json'
      path: '/api/public/openapi.json'
      fullPath: '/api/public/openapi.json'
      preLoaderRoute: typeof ApiPublicOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DevelopersRouteChildren {
  DevelopersApiRoute: typeof DevelopersApiRoute
  DevelopersMcpRoute: typeof DevelopersMcpRoute
  DevelopersIndexRoute: typeof DevelopersIndexRoute
}

const DevelopersRouteChildren: DevelopersRouteChildren = {
  DevelopersApiRoute: DevelopersApiRoute,
  DevelopersMcpRoute: DevelopersMcpRoute,
  DevelopersIndexRoute: DevelopersIndexRoute,
}

const DevelopersRouteWithChildren = DevelopersRoute._addFileChildren(
  DevelopersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DataRoute: DataRoute,
  DataAllRoute: DataAllRoute,
  DevelopersRoute: DevelopersRouteWithChildren,
  EvidenceRoute: EvidenceRoute,
  FailuresRoute: FailuresRoute,
  ImpactRoute: ImpactRoute,
  KeyDataRoute: KeyDataRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  MethodRoute: MethodRoute,
  SettingsRoute: SettingsRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcesRoute: SourcesRoute,
  TrackingRoute: TrackingRoute,
  AgenciesAgencyRoute: AgenciesAgencyRoute,
  BriefDateRoute: BriefDateRoute,
  DayDateRoute: DayDateRoute,
  EventsIdRoute: EventsIdRoute,
  SignalsFamilyRoute: SignalsFamilyRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
  BriefIndexRoute: BriefIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiPublicBriefRoute: ApiPublicBriefRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicOpenapiDotjsonRoute: ApiPublicOpenapiDotjsonRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
